// ============================================================
// DEBATES — each question has your answers and each rival's answer.
// Rival answer: { text, fx: faction gains for that rival, attack: candidateId (optional) }
// An attack costs the target support in every faction and adds to the attacker's debate score.
// ============================================================

const DEBATE_QUESTIONS = [
  { id: 'd_prove', text: 'MODERATOR: "Each of you says you are the true conservative in this race. Name your single most conservative achievement."',
    answers: [
      { text: '"I eliminated the state income tax."', fx: { liberty: 3, chamber: 2 }, fb: 'A strong answer on economic policy, based on a real record.' },
      { text: '"I led the first state deportation program in the country."', fx: { maga: 4, farm: -1 }, fb: 'This speaks to the most important issue for primary voters.' },
      { text: '"I signed the strongest abortion ban in America."', fx: { faith: 3, seniors: 1 }, fb: 'This reminds evangelicals that you delivered on their top issue.' },
      { text: '"I have fought the left on every issue, every day."', fx: { maga: 2, online: 2 }, fb: 'Energetic but vague. The audience responds to the tone more than the content.' },
    ],
    rivals: {
      dunmore: { text: '"I built a movement of two million listeners who are done with the uniparty. The Governor built a budget surplus for the Chamber of Commerce."', fx: { maga: 3, online: 2 }, attack: 'you' },
      rick: { text: '"I have baptized more than four thousand Cimarronians. I have preached the truth when it was unpopular. That is my record."', fx: { faith: 3 } },
      krantz: { text: '"I told the ATF they would be arrested if they came into Harlan County without my permission. They have not come."', fx: { guns: 4, maga: 1 } },
      vaskel: { text: '"I have created 1,400 jobs in Pratt Junction. I have never been on a government payroll. None of these people can say that."', fx: { liberty: 3, chamber: 2 } },
      whitlock: { text: '"I balanced eleven state budgets. Conservatism used to mean paying your bills."', fx: { chamber: 2 } },
    } },
  { id: 'd_bible', text: 'MODERATOR: "Pastor Rick says biblical law should guide state law. Where does each of you stand?"',
    answers: [
      { text: '"Our laws should reflect God\'s law."', fx: { faith: 4, liberty: -3 }, fb: 'Evangelical voters respond strongly. Libertarians are uneasy.' },
      { text: '"Rick, which laws would you enforce, and who would decide?"', fx: { liberty: 2, seniors: 1, opp: { rick: -3 } }, fb: 'Pastor Rick struggles with the follow-up. Some evangelicals think you mocked the question.' },
      { text: '"The Constitution comes first, and it was written by men of faith."', fx: { faith: 2, seniors: 2, guns: 1 }, fb: 'A safe answer that most of the coalition accepts.' },
      { text: '"Rick should explain his church\'s finances before he explains God\'s law."', fx: { maga: 2, faith: -2, opp: { rick: -4 } }, fb: 'A sharp attack. The audience reacts loudly, both ways.' },
    ],
    rivals: {
      dunmore: { text: '"I am a Christian, but I am not running for pastor. I am running to deport criminals and end the uniparty."', fx: { maga: 2, liberty: 1 } },
      rick: { text: '"Every law is someone\'s morality. The only question is whose. I choose God\'s. My opponents choose the Chamber of Commerce\'s."', fx: { faith: 5, online: 1 }, attack: 'you' },
      krantz: { text: '"The Constitution is the law I swore to uphold. It was written by God-fearing men, and that is enough for me."', fx: { guns: 2, seniors: 1 } },
      vaskel: { text: '"Government should be neutral and small. I do not want the state in your church, and I do not want it in your wallet."', fx: { liberty: 3, faith: -2 } },
      whitlock: { text: '"I am a Methodist. I would never want a governor to decide which church is correct."', fx: { chamber: 1, faith: -1 } },
    } },
  { id: 'd_carpet', text: 'MODERATOR: "Mr. Vaskel calls the Governor a career politician. Governor, Mr. Vaskel moved here from California four years ago. Please respond, and then Mr. Vaskel."',
    answers: [
      { text: '"He moved here because of the tax cut I passed."', fx: { liberty: 2, opp: { vaskel: -3 } }, fb: 'Effective. It turns his move into your achievement.' },
      { text: '"Cimarron is not a startup, and it is not for sale."', fx: { farm: 2, seniors: 2, opp: { vaskel: -3 } }, fb: 'The line lands with rural and older voters.' },
      { text: '"He is welcome here, like any American."', fx: { chamber: 2, rino: 1 }, fb: 'Gracious, but it wastes an opening.' },
      { text: '"He gave money to California Democrats for ten years."', fx: { maga: 3, opp: { vaskel: -2 } }, fb: 'It is true, and much of the audience did not know it.' },
    ],
    rivals: {
      dunmore: { text: '"Brent, you gave to Kamala Harris\'s Senate campaign. That is not a startup. That is a confession."', fx: { maga: 2 }, attack: 'vaskel' },
      rick: { text: '"Where a man lived matters less than where he worships. Brent, where do you worship?"', fx: { faith: 2 }, attack: 'vaskel' },
      krantz: { text: '"I have lived in Harlan County for 61 years. I do not need to say more."', fx: { farm: 2, guns: 1 } },
      vaskel: { text: '"I left California because it failed. I came here so Cimarron would not make the same mistakes. The Governor is making them."', fx: { liberty: 3, online: 2 }, attack: 'you' },
      whitlock: { text: '"I welcome Mr. Vaskel. I only wish he had brought his checkbook to the schools and not to the super PACs."', fx: { chamber: 1 } },
    } },
  { id: 'd_arrest', text: 'MODERATOR: "Sheriff Krantz has refused to enforce state laws that he considers unconstitutional. Should a sheriff be allowed to do that?"',
    answers: [
      { text: '"A sheriff who picks which laws to follow should not be governor."', fx: { seniors: 3, chamber: 1, opp: { krantz: -3 } }, fb: 'A clear contrast on the rule of law.' },
      { text: '"Bo is a good sheriff. He is not ready to be governor."', fx: { seniors: 2, guns: 1, opp: { krantz: -2 } }, fb: 'Respectful, and effective with gun owners.' },
      { text: '"I respect any sheriff who stands up to federal overreach."', fx: { guns: 3, opp: { krantz: 1 } }, fb: 'Gun owners approve, but you did not answer the question about state law.' },
      { text: '"Which of my laws does he oppose? The gun law or the tax cut?"', fx: { guns: 2, liberty: 2, opp: { krantz: -2 } }, fb: 'Krantz has no good answer. A strong moment.' },
    ],
    rivals: {
      dunmore: { text: '"The problem is not sheriffs who defy bad laws. The problem is governors who sign them."', fx: { maga: 2, guns: 1 }, attack: 'you' },
      rick: { text: '"There is a higher law than any statute. A man of conscience must follow it."', fx: { faith: 2, guns: 1 } },
      krantz: { text: '"I took an oath to the Constitution, not to the Governor. When the Governor violates it, I will not help him."', fx: { guns: 5, liberty: 1 }, attack: 'you' },
      vaskel: { text: '"Rule of law matters to investors. But a sheriff is closer to the people than any bureaucrat in the capital."', fx: { liberty: 1 } },
      whitlock: { text: '"No. Laws are made by the legislature and reviewed by courts. That is how a republic works."', fx: { chamber: 2, seniors: 1 } },
    } },
  { id: 'd_chamber', text: 'MODERATOR: "Lt. Governor Dunmore says the Governor is controlled by the Chamber of Commerce. Is big business an ally or an enemy of conservatives today?"',
    answers: [
      { text: '"The Chamber fought my deportation program. Ask them who controls me."', fx: { maga: 3, chamber: -3 }, fb: 'Your record defeats the attack.' },
      { text: '"Travis has spent four years on a podcast. I have spent four years governing."', fx: { seniors: 3, chamber: 1, opp: { dunmore: -3 } }, fb: 'A strong contrast between experience and media.' },
      { text: '"Business creates jobs. I am proud to work with employers."', fx: { chamber: 4, rino: 2, maga: -3 }, fb: 'A traditional Republican answer. In this primary it confirms the attack.' },
      { text: '"Travis, your show is sponsored by a company with ties to China."', fx: { maga: 2, opp: { dunmore: -5 } }, fb: 'Dunmore denies it angrily. Reporters will check it tomorrow.' },
    ],
    rivals: {
      dunmore: { text: '"Big business wants cheap foreign labor and woke HR departments. They are not our allies. They are the other side with better lawyers."', fx: { maga: 4, online: 2, chamber: -2 } },
      rick: { text: '"Corporations that celebrate sin in June should not expect our votes in November."', fx: { faith: 3 } },
      krantz: { text: '"I do not care who is big or small. I care who follows the Constitution."', fx: { guns: 1 } },
      vaskel: { text: '"I am a businessman. The enemy is not business. The enemy is a government that makes business impossible."', fx: { liberty: 3, chamber: 2, maga: -1 } },
      whitlock: { text: '"Employers are our neighbors. When did we start hating the people who sign paychecks?"', fx: { chamber: 3, maga: -2 } },
    } },
  { id: 'd_compromise', text: 'FMR. SEN. WHITLOCK asks the other candidates: "Is there any issue on which you would work with Democrats?"',
    answers: [
      { text: '"No."', fx: { maga: 3, online: 2 }, fb: 'The loudest applause of the night.' },
      { text: '"Not while they support open borders and abortion."', fx: { maga: 2, faith: 2 }, fb: 'A firm answer, with reasons.' },
      { text: '"On roads and water, yes."', fx: { rino: 2, farm: 2, seniors: 1, maga: -2 }, fb: 'Reasonable, and Whitlock thanks you. That will hurt you.' },
      { text: '"Compromise is how we lost the country."', fx: { online: 3, maga: 1 }, fb: 'This connects with the anger of the base.' },
    ],
    rivals: {
      dunmore: { text: '"Carol, the Democrats want to put your grandchildren in drag shows. No, I will not work with them."', fx: { maga: 3, online: 2 }, attack: 'whitlock' },
      rick: { text: '"There is no compromise between good and evil."', fx: { faith: 3, online: 1 } },
      krantz: { text: '"I have worked with Democratic sheriffs on drug cases. That is the only thing I will work with them on."', fx: { guns: 1, seniors: 1 } },
      vaskel: { text: '"I would work with anyone to cut regulations. It turns out that is nobody in either party."', fx: { liberty: 2 } },
      whitlock: { text: '"I worked with Democrats to build the Sumner water project. Every farmer on this stage uses it."', fx: { farm: 2, chamber: 1, maga: -1 } },
    } },
  { id: 'd_accept', text: 'MODERATOR: "Lightning round. Will you accept the result of this primary, and support the nominee?"',
    answers: [
      { text: '"If the election is fair."', fx: { maga: 4, online: 2, seniors: -1 }, fb: 'What most of the base wants to hear. It will be quoted if you lose.' },
      { text: '"Yes."', fx: { rino: 2, maga: -2 }, fb: 'Some in the audience react with suspicion.' },
      { text: '"I expect to win, so the question does not apply."', fx: { maga: 2 }, fb: 'Confident, but not an answer.' },
      { text: '"I will accept it, and I will support the nominee."', fx: { seniors: 2, chamber: 1, rino: 1 }, fb: 'Older voters respect the commitment.' },
    ],
    rivals: {
      dunmore: { text: '"I will accept a clean election. We will have observers in every county."', fx: { maga: 3, online: 1 } },
      rick: { text: '"I accept God\'s will. I will also have lawyers."', fx: { faith: 1, maga: 1 } },
      krantz: { text: '"My deputies will be at the polls in Harlan County to make sure it is fair."', fx: { guns: 2, seniors: -1 } },
      vaskel: { text: '"Yes. Markets accept results, and so should candidates."', fx: { liberty: 1, maga: -1 } },
      whitlock: { text: '"Yes, without conditions. It is sad that this is now a hard question."', fx: { chamber: 2, maga: -2 } },
    } },
  { id: 'd_democrat', text: 'MODERATOR: "Name one thing you respect about the Democratic Party."',
    answers: [
      { text: '"Nothing."', fx: { maga: 3 }, fb: 'The audience cheers.' },
      { text: '"The Democrats of JFK\'s time. Not today\'s party."', fx: { seniors: 3 }, fb: 'A familiar answer that older voters like.' },
      { text: '"Their discipline. They vote together. We should learn from that."', fx: { online: 3, maga: 1 }, fb: 'A strategic answer that the New Right respects.' },
      { text: '"Many Democrats love their country. We just disagree."', fx: { rino: 2, chamber: 1 }, fb: 'Gracious. In this room it sounds weak.' },
    ],
    rivals: {
      dunmore: { text: '"They fight for their people. Our side sends thoughts and prayers and then funds Ukraine."', fx: { maga: 2, online: 3 } },
      rick: { text: '"I respect the Democrats who have left that party. There are more every year."', fx: { faith: 2, seniors: 1 } },
      krantz: { text: '"Some of them hunt."', fx: { guns: 2, farm: 1 } },
      vaskel: { text: '"Their technology operation. Ours is ten years behind, and I intend to fix that."', fx: { online: 2, liberty: 1 } },
      whitlock: { text: '"My late husband was a Democrat for forty years. He was the finest man I ever knew."', fx: { seniors: 1, maga: -2 } },
    } },
  { id: 'd_deport_num', text: 'MODERATOR: "Every candidate has promised deportations. How many people would you deport, and what happens to the plants and farms that lose their workers?"',
    answers: [
      { text: '"Every person who is here illegally. Employers will adjust."', fx: { maga: 4, online: 2, farm: -2 }, fb: 'The strongest answer. Farmers wonder who will work their fields.' },
      { text: '"More than all my opponents combined, because I have already done it."', fx: { maga: 3, opp: { dunmore: -1 } }, fb: 'Your record gives this answer weight.' },
      { text: '"Criminals first. Then we fix the legal system."', fx: { seniors: 2, rino: 1, maga: -2 }, fb: 'Dunmore says this is "the answer Democrats give."' },
      { text: '"The number depends on federal cooperation."', fx: { rino: 1, maga: -1 }, fb: 'Honest, but it sounds like an excuse.' },
    ],
    rivals: {
      dunmore: { text: '"All of them. Every single one. And if a plant cannot survive without illegal labor, it does not deserve to survive."', fx: { maga: 5, online: 2, farm: -2, chamber: -2 } },
      rick: { text: '"We must enforce the law, and our churches will care for families who are affected."', fx: { faith: 2, maga: 1 } },
      krantz: { text: '"My deputies have already turned over 300 people to ICE. I do not make promises. I make arrests."', fx: { guns: 3, maga: 2 } },
      vaskel: { text: '"Deport criminals, and give H-1B visas to the best engineers in the world. We need both."', fx: { liberty: 2, chamber: 2, maga: -3 } },
      whitlock: { text: '"The Garnett plant lost 40% of its workers this year. Somebody on this stage should talk about that honestly."', fx: { farm: 2, chamber: 2, maga: -3 }, attack: 'you' },
    } },
  { id: 'd_institutions', text: 'MODERATOR: "The New Right says conservatives must take control of universities, the media and the civil service. Do you agree?"',
    answers: [
      { text: '"Yes. We lost them to the left, and we must take them back."', fx: { online: 4, maga: 2, liberty: -2 }, fb: 'The New Right hears you speaking its language.' },
      { text: '"We should not take them. We should defund them."', fx: { liberty: 3, maga: 1 }, fb: 'The small-government answer. The New Right thinks it is too passive.' },
      { text: '"We must reform them, starting with the universities."', fx: { online: 2, seniors: 1, faith: 1 }, fb: 'A measured version of the same idea.' },
      { text: '"Government should be neutral. That is the conservative principle."', fx: { rino: 2, liberty: 1, online: -4 }, fb: 'The New Right considers this the failed approach of the old party.' },
    ],
    rivals: {
      dunmore: { text: '"Take them? We should fire every bureaucrat who voted against the President and replace them tomorrow."', fx: { maga: 3, online: 3, seniors: -1 } },
      rick: { text: '"We need to take back the schools first. The universities are lost."', fx: { faith: 2, online: 1 } },
      krantz: { text: '"I would start with the Department of Natural Resources."', fx: { guns: 2, farm: 1 } },
      vaskel: { text: '"Replace the civil service with software. You cannot capture an institution that no longer exists."', fx: { liberty: 3, online: 2, seniors: -1 } },
      whitlock: { text: '"Every time one side captures an institution, the other side captures it back. That is not governing."', fx: { chamber: 1, online: -2 } },
    } },
  { id: 'd_tariffs', text: 'MODERATOR: "Soybean prices are down 30% because of the trade war. Farmers in Sumner Valley are losing their land. Do you still support the President\'s tariffs?"',
    answers: [
      { text: '"Yes. China cheated for thirty years. We will not surrender now."', fx: { maga: 4, pres: 3, farm: -2 }, fb: 'Loyal and forceful. Farmers hear no plan.' },
      { text: '"Yes, and I have proposed a state relief fund for farmers."', fx: { farm: 4, maga: 1, liberty: -2 }, fb: 'You protect both flanks. It is the best answer available on this stage.' },
      { text: '"Tariffs are a tax on our own people."', fx: { liberty: 4, chamber: 3, maga: -5, pres: -6, rino: 2 }, fb: 'Economically sound, politically very costly.' },
      { text: '"I support the President. Farmers will be made whole by Washington."', fx: { maga: 2, farm: 1, pres: 2 }, fb: 'A hopeful answer that depends on others.' },
    ],
    rivals: {
      dunmore: { text: '"Farmers are patriots. They know this is a war with China, and wars have costs."', fx: { maga: 3, farm: -2 } },
      rick: { text: '"We should pray for our farmers, and our churches are already feeding families in Sumner."', fx: { faith: 2, farm: 1 } },
      krantz: { text: '"I am a rancher. I lost money this year. I still support the President."', fx: { farm: 3, maga: 2 } },
      vaskel: { text: '"Tariffs are bad economics. I will say it even if it costs me."', fx: { liberty: 3, chamber: 2, maga: -3 } },
      whitlock: { text: '"The Sumner Valley lost $400 million this year. Someone must say that this policy has failed."', fx: { farm: 2, chamber: 2, maga: -4 } },
    } },
  { id: 'd_closing', text: 'MODERATOR: "Closing statements. Thirty seconds each. Why should Cimarron Republicans choose you?"',
    answers: [
      { text: '"I did not just talk. I governed. Four years of results, and I am not finished."', fx: { seniors: 3, chamber: 1, maga: 1 }, fb: 'A strong incumbent close.' },
      { text: '"Every one of them says they will fight. I am the only one who already has."', fx: { maga: 3, guns: 1 }, fb: 'Combines your record with the language of the base.' },
      { text: '"This is a fight for the soul of our state. I will not back down."', fx: { faith: 2, online: 2, maga: 1 }, fb: 'Emotional and effective with activists.' },
      { text: '"I will be governor for every Cimarronian, not only the loudest ones."', fx: { rino: 3, chamber: 2, maga: -3 }, fb: 'A general-election message in a primary.' },
    ],
    rivals: {
      dunmore: { text: '"The establishment has had four years. Give the movement four."', fx: { maga: 3, online: 2 }, attack: 'you' },
      rick: { text: '"I do not want your vote for me. I want it for the Lord, and for your children."', fx: { faith: 4 } },
      krantz: { text: '"I have kept Harlan County free for sixteen years. I can do it for the whole state."', fx: { guns: 3, farm: 1 } },
      vaskel: { text: '"Every other candidate on this stage has spent your money. I have made money. Let me make it for you."', fx: { liberty: 3, chamber: 1 } },
      whitlock: { text: '"I will not win tonight. But one day this party will want to be serious again, and I will have been here."', fx: { chamber: 2, seniors: 1 } },
    } },
];
