// ============================================================
// QUESTIONS — regular campaign questions + rival news wire.
// ============================================================

// ---------- Questions ----------
// fx keys: faction ids (your appeal), rino (RINO label), pres (President's opinion),
//          money ($M), opp: { candidateId: delta to all factions }, flag: 'name'
// cond: s => boolean.  priority: true = asked as soon as cond is true (from step 3).
const has = (s, f) => !!s.flags[f];

const QUESTIONS = [
  { id: 'deport', setting: 'Town Hall · Osgood', region: 'osgood',
    text: 'A voter asks: "Dunmore has promised to deport every illegal immigrant in Cimarron within his first year. Will you match that promise?"',
    answers: [
      { text: 'Yes. Every one, and we will use the National Guard to do it.',
        fx: { maga: 5, online: 3, farm: -3, chamber: -3, pres: 3 },
        fb: 'This closes the gap with Dunmore on his strongest issue. Dairy and meatpacking employers will read it as a direct threat to their workforce.' },
      { text: 'Operation Heartland has already removed 4,000 people. We will expand it.',
        fx: { maga: 2, guns: 1, seniors: 1 },
        fb: 'A safe answer that is based on your record. It does not excite anyone, but it gives Dunmore nothing to attack.' },
      { text: 'We deport criminals first, and create a legal guest-worker path for agriculture.',
        fx: { farm: 4, chamber: 4, maga: -6, rino: 3 },
        fb: 'The Farm Bureau is relieved. Dunmore will call this "amnesty" within the hour, and in this primary that label is hard to remove.' },
      { text: 'We will build a state detention facility so that no one is released while they wait.',
        fx: { maga: 4, online: 5, seniors: -1, chamber: -2, flag: 'alcatraz' },
        fb: 'This is a concrete promise that activists can rally around. The facility will cost money and bring national media attention, and some of it will be negative.' },
    ] },
  { id: 'travel_ban', setting: 'Family Policy Council Forum · Caney Ridge', region: 'bible',
    text: 'Cimarron bans abortion from conception. The moderator asks: "Pastor Rick supports a law that would make it a crime to help a minor travel out of state for an abortion. Would you sign it?"',
    answers: [
      { text: 'Yes. And I would extend it to adults.',
        fx: { faith: 5, online: 3, liberty: -4, seniors: -2 },
        fb: 'The pro-life movement will see this as the strongest position in the race. Liberty Caucus voters worry about how the state would enforce it.' },
      { text: 'Yes, for minors. Parents have a right to know.',
        fx: { faith: 3, maga: 1, liberty: -1 },
        fb: 'This matches the laws other states have passed. The Family Policy Council considers it the minimum acceptable answer.' },
      { text: 'Our law is already one of the strongest in the nation. I will enforce it.',
        fx: { faith: -5, chamber: 2, rino: 2 },
        fb: 'Pastor Rick will say you are "content with the status quo." For many evangelical voters, that is a disqualifying answer.' },
      { text: 'Yes, and we should also restrict IVF procedures that destroy embryos.',
        fx: { faith: 4, online: 2, seniors: -3, farm: -2, maga: -2 },
        fb: 'This wins the most committed pro-life activists. Many Republican families have used IVF, and polling shows this position loses support across the coalition.' },
    ] },
  { id: 'badminton', setting: 'Interview · Cimarron Ledger',
    text: '"The state activities association reports one transgender athlete in girls\' high school sports. Sheriff Krantz wants a state task force to enforce the ban. What is your plan?"',
    answers: [
      { text: 'Create the task force. The law must be enforced.',
        fx: { guns: 3, maga: 3, online: 2, money: -.1 },
        fb: 'This is a strong enforcement signal to the base. Critics will say the state is putting police resources on one student.' },
      { text: 'Require sex verification for all girls in school sports.',
        fx: { faith: 2, maga: 2, seniors: -2, farm: -1 },
        fb: 'This closes every loophole. Some parents in the suburbs and small towns are uncomfortable with the physical checks it requires.' },
      { text: 'The ban is already law. This is one student, and we should focus on other issues.',
        fx: { rino: 4, chamber: 2, maga: -5, online: -5 },
        fb: 'This reads as retreat on a defining cultural issue. Dunmore and the New Right will say you are "not willing to fight."' },
      { text: 'I signed the ban and I will defend it in every court.',
        fx: { maga: 3, faith: 2 },
        fb: 'This keeps the focus on your record. The answer is strong and gives your opponents little to attack.' },
    ] },
  { id: 'stolen', setting: 'Patriot Radio 1340 AM · Lake Cheney', region: 'cheney',
    text: 'The host asks: "Governor, do you believe the 2020 presidential election was stolen?"',
    answers: [
      { text: 'Yes. And it has not been fixed.',
        fx: { maga: 4, online: 3 },
        fb: 'This is the answer most primary voters want. It ends the question for the base, but it will follow you into the general election.' },
      { text: 'There was massive fraud, and that is why I signed our election integrity law.',
        fx: { maga: 5, seniors: 1 },
        fb: 'This combines the base\'s belief with your record. It is the most effective answer available.' },
      { text: 'Cimarron\'s elections are secure. I trust our county clerks.',
        fx: { rino: 3, chamber: 2, maga: -6 },
        fb: 'This is true for Cimarron, but the base hears it as a refusal to answer. Dunmore will use it in every debate.' },
      { text: 'We should ban voting machines and hand-count every ballot.',
        fx: { maga: 3, seniors: 3, money: -.05 },
        fb: 'Election activists will be energized. County clerks, most of them Republicans, warn that full hand counts would delay results by weeks.' },
    ] },
  { id: 'measles', setting: 'Press Conference · Capitol',
    text: '"There is a measles outbreak in Cloud County. Forty children are infected. Some Republicans want to end school vaccine requirements. What is your position?"',
    answers: [
      { text: 'End the mandates. Parents, not the state, make medical decisions.',
        fx: { maga: 3, online: 3, liberty: 3, seniors: -3 },
        fb: 'Health-freedom activists see this as a major win. Public health officials warn that the outbreak could spread, and older voters are worried.' },
      { text: 'Keep the requirements during the outbreak. This is a public health emergency.',
        fx: { rino: 2, seniors: 3, maga: -3 },
        fb: 'Responsible, and older voters appreciate it. The health-freedom movement will call it "COVID all over again."' },
      { text: 'Keep the requirements, but expand religious and personal exemptions.',
        fx: { maga: 2, online: 2, farm: 2, seniors: -1 },
        fb: 'A middle position that most of the base accepts. Doctors say exemptions are why the outbreak started.' },
      { text: 'This is a time for prayer and for parents to protect their families.',
        fx: { faith: 4 },
        fb: 'Evangelical voters respond well. You have avoided taking a policy position, and reporters will notice.' },
    ] },
  { id: 'soybeans', setting: 'Farm Bureau Breakfast · Sumner Valley', region: 'sumner',
    text: '"The President\'s tariffs caused China to stop buying our soybeans. Prices are down 30%. Do you support the tariffs?"',
    answers: [
      { text: 'Completely. We have to stand up to China, even if it hurts in the short term.',
        fx: { maga: 4, pres: 5, farm: -4 },
        fb: 'The President\'s team will notice this loyalty. Farmers in the room hear that their losses are acceptable to you.' },
      { text: 'Yes, and the state will create a relief fund for affected farmers.',
        fx: { farm: 5, maga: 1, liberty: -4, money: -.1 },
        fb: 'This protects you with farmers without breaking with the President. Vaskel and the Liberty Caucus will call it a bailout.' },
      { text: 'No. Tariffs are a tax on Cimarron families and farmers.',
        fx: { liberty: 5, chamber: 5, farm: 2, maga: -6, pres: -8, rino: 2 },
        fb: 'This is the traditional free-market position. In this primary it is also a direct break with the President, and he will remember it.' },
      { text: 'China is responsible for this, not the President.',
        fx: { maga: 2, farm: 1 },
        fb: 'This deflects without making a policy commitment. Farmers wanted a plan.' },
    ] },
  { id: 'drag', setting: 'Interview · KCIM-TV Channel 4',
    text: '"A public library in Lawrenceville hosted a drag story hour for children. Hundreds of protesters and counter-protesters came. What should the state do?"',
    answers: [
      { text: 'Cut state funding to any library that hosts these events.',
        fx: { faith: 3, maga: 3, seniors: -1 },
        fb: 'This is a clear position with a clear enforcement tool. Rural libraries worry they will lose funding for unrelated reasons.' },
      { text: 'Prosecute these performances under the state obscenity law.',
        fx: { faith: 3, guns: 2, online: 2, liberty: -4 },
        fb: 'This is the most aggressive option. The legal outcome is uncertain, and the Liberty Caucus is concerned about free speech.' },
      { text: 'Sign a law that bans drag performances where minors are present.',
        fx: { faith: 3, maga: 2, online: 1 },
        fb: 'Several states have passed similar laws. It is popular with the base and likely to face a court challenge.' },
      { text: 'Parents who brought their children made that choice. The state should not decide.',
        fx: { liberty: 3, rino: 3, faith: -5, maga: -3 },
        fb: 'A consistent libertarian answer. In this primary, most voters will hear it as indifference.' },
    ] },
  { id: 'christian_nat', setting: 'Interview · Cimarron Ledger',
    text: 'The reporter asks: "Pastor Rick calls himself a Christian nationalist. Are you one?"',
    answers: [
      { text: 'Yes. This nation was built on Christian principles, and our laws should reflect them.',
        fx: { faith: 5, online: 3, liberty: -3, chamber: -3 },
        fb: 'This takes away Pastor Rick\'s main difference from you. Business donors and libertarians are uneasy.' },
      { text: 'I am a Christian and I love my country. I do not need a label.',
        fx: { faith: 2, maga: 2 },
        fb: 'This avoids the label without giving offense. Most voters accept it.' },
      { text: 'America was founded as a Christian nation, and we must return to that.',
        fx: { faith: 3, seniors: 3 },
        fb: 'Older conservatives respond strongly. Historians will dispute the claim, but they do not vote in this primary.' },
      { text: 'I support the separation of church and state.',
        fx: { rino: 3, liberty: 2, faith: -6 },
        fb: 'Constitutionally sound. Pastor Rick\'s network will use it to tell evangelicals that you are not one of them.' },
    ] },
  { id: 'teachers_carry', setting: 'Rifle Association Banquet · Harlan', region: 'harlan',
    text: 'The Rifle Association\'s candidate questionnaire asks: "Should teachers be allowed to carry firearms in school?"',
    answers: [
      { text: 'Yes, and the state should pay for training and equipment.',
        fx: { guns: 5, maga: 2, seniors: -1 },
        fb: 'This earns you the highest rating the Association gives. Teachers\' groups and some school boards will oppose it.' },
      { text: 'Yes, where local school boards approve it.',
        fx: { guns: 3, chamber: 1 },
        fb: 'A popular, moderate version of the policy. The Association will note that you did not go further.' },
      { text: 'Yes, and lower the age for concealed carry to 18.',
        fx: { guns: 3, online: 4, seniors: -4, faith: -2 },
        fb: 'Young activists support it. Many older voters and some sheriffs think it goes too far.' },
      { text: 'We should fund armed school resource officers instead.',
        fx: { rino: 1, guns: 1, seniors: 2 },
        fb: 'A reasonable policy. The Association will rate you lower than Krantz.' },
    ] },
  { id: 'university', setting: 'Board of Regents Meeting · Lawrenceville', region: 'lawrence',
    text: '"The state university closed its DEI office after your executive order, but the same staff now work in an \'Office of Belonging.\' What will you do?"',
    answers: [
      { text: 'Replace the Board of Regents with conservative reformers.',
        fx: { online: 6, maga: 2, chamber: -3 },
        fb: 'Florida did this at New College. The New Right sees it as the model. Business leaders worry about the university\'s accreditation.' },
      { text: 'Eliminate any department that promotes DEI ideology.',
        fx: { maga: 3, faith: 2 },
        fb: 'This is a clear promise. Faculty will resist, and enforcement will be contested.' },
      { text: 'Cut the university\'s state funding until it complies.',
        fx: { liberty: 4, chamber: 2, maga: -2, opp: { vaskel: 2 } },
        fb: 'Fiscal conservatives support it. Some rural voters depend on the university\'s extension services.' },
      { text: 'Create a new School of Civic Thought to teach Western civilization.',
        fx: { faith: 2, online: 3, seniors: 2 },
        fb: 'Several red states have built similar schools. It is constructive and popular across the coalition.' },
    ] },
  { id: 'pardons', setting: 'Interview · Patriot Radio 1340 AM',
    text: '"Last year, hundreds of protesters broke into the state Capitol to stop a vote on a fee increase. Twelve are in prison. Will you pardon them?"',
    answers: [
      { text: 'Yes, all of them. They were protesting government overreach.',
        fx: { maga: 5, online: 3, guns: 2, chamber: -3, seniors: -2, flag: 'pardons' },
        fb: 'The base sees them as political prisoners. Some older and law-and-order voters see a pardon as rewarding violence.' },
      { text: 'I will pardon those who did not commit violence.',
        fx: { maga: 2, rino: 1 },
        fb: 'A compromise that most voters accept. Activists will argue about where you draw the line.' },
      { text: 'No. They broke into the Capitol and attacked officers.',
        fx: { rino: 3, seniors: 2, maga: -5 },
        fb: 'A law-and-order answer. Dunmore will call it "weaponization of justice" and compare you to federal prosecutors.' },
      { text: 'Full pardons, and a state investigation of how they were prosecuted.',
        fx: { maga: 4, online: 5, chamber: -5, seniors: -3, flag: 'pardons' },
        fb: 'This makes their cause yours. It is the strongest possible signal to the base, and it will define you nationally.' },
    ] },
  { id: 'property_tax', setting: 'Senior Center · Lake Cheney', region: 'cheney',
    text: 'A retired teacher asks: "My property tax went up 40% in three years. What will you do about it?"',
    answers: [
      { text: 'Abolish property taxes completely.',
        fx: { liberty: 5, seniors: 4, farm: 3, chamber: -2, flag: 'no_prop_tax' },
        fb: 'This is the most popular promise in the race. County officials say it would remove half of all school funding, with no replacement named.' },
      { text: 'Freeze property taxes for homeowners over 65.',
        fx: { seniors: 6, liberty: -1 },
        fb: 'Older voters love it. It moves the tax burden to younger families.' },
      { text: 'Replace property taxes with a higher sales tax.',
        fx: { chamber: 2, liberty: 2, seniors: 1, maga: -1 },
        fb: 'Economists call it regressive. It is a real plan, which most of your rivals do not have.' },
      { text: 'School boards are raising taxes. We will cap their levies.',
        fx: { maga: 3, faith: 2 },
        fb: 'This turns voter anger toward school boards. The boards will say the cuts will come from teachers.' },
    ] },
  { id: 'wind', setting: 'County Fair · Sumner Valley', region: 'sumner',
    text: 'Farmers want to lease land to wind companies for $12,000 per turbine per year. Dunmore wants a ban on new wind farms. A farmer asks for your position.',
    answers: [
      { text: 'I will sign a moratorium on new wind projects.',
        fx: { maga: 4, online: 2, farm: -5 },
        fb: 'This aligns you with the energy populists. Farmers lose a major source of income, and some see it as an attack on property rights.' },
      { text: 'It is the farmer\'s land and the farmer\'s choice.',
        fx: { farm: 5, liberty: 4, maga: -3 },
        fb: 'Property-rights conservatives agree. Dunmore will say you support "green energy subsidies."' },
      { text: 'Allow them, but end all state subsidies and tax breaks for wind.',
        fx: { farm: 2, liberty: 2, chamber: 1 },
        fb: 'A position that respects property rights and opposes subsidies. It satisfies most factions partly.' },
      { text: 'Cimarron is an oil and gas state. Wind is not our future.',
        fx: { maga: 3, farm: -2, chamber: 1 },
        fb: 'The energy industry is pleased. Farmers in Sumner Valley feel dismissed.' },
    ] },
  { id: 'rick_jet', setting: 'Press Conference · Fort Eisenhower Airport', region: 'fort',
    text: '"Pastor Rick\'s church owns a $60 million private jet that is exempt from state taxes. Critics say it is used for personal travel. Will you criticize him?"',
    answers: [
      { text: 'Voters deserve to know how a candidate uses tax-exempt money.',
        fx: { faith: -2, maga: 2, liberty: 1, opp: { rick: -5 } },
        fb: 'This hurts Pastor Rick with voters outside his church. Some evangelicals see it as an attack on the church itself.' },
      { text: 'I will not attack a man\'s ministry.',
        fx: { faith: 3 },
        fb: 'Evangelical voters respect this. Pastor Rick will continue attacking you.' },
      { text: 'That is between Pastor Rick and his congregation.',
        fx: { faith: 1, chamber: 1, opp: { rick: 1 } },
        fb: 'A neutral answer. It gives up an opportunity.' },
      { text: 'Church aircraft used for personal travel should be taxed.',
        fx: { faith: -4, liberty: -2, chamber: 1, opp: { rick: -3 } },
        fb: 'Pastor Rick\'s network will say you want to tax churches. That message will reach every congregation in the state by Sunday.' },
    ] },
  { id: 'freedomopolis', setting: 'Tech Forum · Pratt Junction', region: 'pratt',
    text: '"Brent Vaskel wants the legislature to exempt his charter city from state labor, zoning and tax law. What do you think of the project?"',
    answers: [
      { text: 'No billionaire should be allowed to write his own laws.',
        fx: { maga: 2, seniors: 2, opp: { vaskel: -5 } },
        fb: 'A populist attack that works with most voters. Vaskel\'s allies in the tech-right will respond with a lot of money.' },
      { text: 'Charter cities are an interesting experiment in freedom.',
        fx: { liberty: 3, online: 1, opp: { vaskel: 2 } },
        fb: 'This appeals to libertarians. It also makes Vaskel\'s central idea look more acceptable.' },
      { text: 'Cimarron law applies in every part of Cimarron. No exceptions.',
        fx: { guns: 3, maga: 3, liberty: -4, opp: { vaskel: -3 } },
        fb: 'A strong sovereignty argument. The Liberty Caucus notes that you have supported exemptions for other businesses.' },
      { text: 'I would consider it if it creates jobs for Cimarron workers.',
        fx: { liberty: 2, chamber: 2 },
        fb: 'A pragmatic answer. It does not help you or hurt Vaskel.' },
    ] },
  { id: 'krantz_sheriff', setting: 'Interview · KCIM-TV Channel 4',
    text: '"Sheriff Krantz says the county sheriff is the highest law enforcement authority in the county, above the Governor and federal agents. Do you agree?"',
    answers: [
      { text: 'Sheriffs are important, but the Constitution does not place them above state law.',
        fx: { seniors: 2, guns: -2, rino: 1, opp: { krantz: -2 } },
        fb: 'Legally correct. Many gun owners see sheriffs as their last protection against federal agencies.' },
      { text: 'He has refused to enforce laws I signed. That is not conservatism. It is lawlessness.',
        fx: { seniors: 2, chamber: 1, guns: -1, opp: { krantz: -4 } },
        fb: 'A direct hit on his record. It frames the race as order against disorder.' },
      { text: 'Yes. Sheriffs are the last line of defense against federal overreach.',
        fx: { guns: 4, maga: 1, chamber: -2, opp: { krantz: 2 } },
        fb: 'Gun owners agree. You have also endorsed the central argument of Krantz\'s campaign.' },
      { text: 'I will sign a law that protects sheriffs who resist federal gun laws.',
        fx: { guns: 3, liberty: 3, online: 1 },
        fb: 'This takes Krantz\'s issue without accepting his theory. Gun owners respond well.' },
    ] },
  { id: 'podcast', setting: 'Campaign Headquarters · Fort Eisenhower', region: 'fort',
    text: 'Your digital director reports that Dunmore\'s podcast episode "Is the Governor Really a Conservative?" has been downloaded 400,000 times. How do you respond?',
    answers: [
      { text: 'Start our own weekly show and go directly to voters.',
        fx: { online: 4, maga: 2, money: -.05, flag: 'podcast' },
        fb: 'Alternative media is where these voters are. It will take time and staff to build an audience.' },
      { text: 'Go on his show and debate him directly.',
        fx: { maga: 3, online: 2, opp: { dunmore: -2 } },
        fb: 'This is risky on his platform, but it shows confidence. His audience respects a candidate who does not avoid him.' },
      { text: 'Attack his record. He has passed no legislation in four years.',
        fx: { chamber: 2, seniors: 2, opp: { dunmore: -3 } },
        fb: 'A fair point that older voters understand. His audience does not care about legislation.' },
      { text: 'Do not respond. It gives him attention.',
        fx: { maga: -2, online: -2 },
        fb: 'His audience will hear only his side. Silence reads as weakness.' },
    ] },
  { id: 'whitlock_extreme', setting: 'Press Conference · Capitol',
    text: '"Former Senator Whitlock says you have become \'dangerously extreme.\' How do you respond?"',
    answers: [
      { text: 'Coming from Carol Whitlock, I take that as a compliment.',
        fx: { maga: 4, online: 3, faith: 2 },
        fb: 'An attack from the establishment helps you with the base. This is one of your best moments of the campaign.' },
      { text: 'I am in the mainstream of the Republican Party. The party has changed.',
        fx: { maga: 2, seniors: 2 },
        fb: 'An accurate description of the electorate. It is calm and effective.' },
      { text: 'Carol and I agree on more than people think.',
        fx: { rino: 5, chamber: 3, maga: -5 },
        fb: 'This is a serious mistake in this primary. Dunmore will put the quote in an ad.' },
      { text: 'I will not respond to a candidate at 4%.',
        fx: { online: 3, maga: 2 },
        fb: 'Dismissive, but effective. It keeps attention on your real opponents.' },
    ] },
  { id: 'meatpacking', cond: s => has(s, 'raids') || has(s, 'alcatraz'), priority: true,
    setting: 'Garnett Pork Plant · Pratt Junction', region: 'pratt',
    text: 'After state immigration enforcement, the Garnett Pork plant has lost 40% of its workforce. It may close a production line. The plant manager asks for help.',
    answers: [
      { text: 'Loosen child labor laws so that 14- and 15-year-olds can work more hours.',
        fx: { chamber: 4, farm: 2, seniors: -2, faith: -1, flag: 'child_labor' },
        fb: 'Iowa and Arkansas passed similar laws. Employers support it. Some parents and faith leaders are uncomfortable.' },
      { text: 'Expand inmate work programs to fill the jobs.',
        fx: { guns: 2, chamber: 3, maga: 1 },
        fb: 'Law-and-order voters see it as responsible. Civil liberties groups compare it to forced labor.' },
      { text: 'Continue enforcement. American workers will fill these jobs at the right wage.',
        fx: { maga: 4, online: 2, chamber: -4, farm: -3 },
        fb: 'This is consistent with your promises. If the line closes, 600 jobs will be lost in Pratt Junction.' },
      { text: 'Ask Washington for more H-2 visas for meatpacking.',
        fx: { chamber: 5, farm: 4, maga: -5, rino: 3 },
        fb: 'This solves the problem for employers. Dunmore will say you want to replace deported workers with foreign workers.' },
    ] },
  { id: 'alcatraz_citizen', cond: s => has(s, 'alcatraz'), priority: true,
    setting: 'Press Conference · State Detention Facility',
    text: '"A man held for six weeks at the new state detention facility is a U.S. citizen and a Navy veteran from Harlan County. He is suing the state. What is your response?"',
    answers: [
      { text: 'Mistakes can happen in any large operation. The program will continue.',
        fx: { maga: 2, seniors: -3, guns: -1 },
        fb: 'The base accepts this. Veterans\' groups and older voters are angry about how he was treated.' },
      { text: 'We will review the case, but I will not let it stop enforcement.',
        fx: { maga: 1, seniors: -1 },
        fb: 'A controlled answer. The story will stay in the news while the lawsuit continues.' },
      { text: 'He was not properly documented. That is his responsibility.',
        fx: { online: 3, maga: 2, seniors: -4, guns: -2 },
        fb: 'The New Right approves. Many voters think a citizen and veteran should not have to prove his status in detention.' },
      { text: 'I apologize. The state will compensate him and add new safeguards.',
        fx: { rino: 2, seniors: 3, guns: 2, maga: -3, money: -.1 },
        fb: 'This is the right thing to do for him, and veterans notice. Dunmore will call the payment a "settlement for illegal-alien lawyers."' },
    ] },
  { id: 'social_media', setting: 'Parents\' Rights Forum · Osgood', region: 'osgood',
    text: '"Should Cimarron require age verification for social media and adult websites? It would require ID checks for all users."',
    answers: [
      { text: 'Yes. We must protect children, even if adults must show ID.',
        fx: { faith: 3, seniors: 3, liberty: -4, online: -3 },
        fb: 'Parents\' groups and churches support it. Libertarians and young conservatives see it as surveillance.' },
      { text: 'No. It violates free speech and privacy.',
        fx: { liberty: 4, online: 3, faith: -2 },
        fb: 'A principled position. The parents in the room wanted action.' },
      { text: 'Yes for adult websites. For social media, parents should decide.',
        fx: { faith: 2, seniors: 1, liberty: 1 },
        fb: 'A balanced answer. Several red states have passed exactly this.' },
      { text: 'Ban Chinese-owned apps like TikTok first.',
        fx: { maga: 3, online: 2 },
        fb: 'This frames the issue as national security. It avoids the harder question.' },
    ] },
  { id: 'esg', setting: 'Club for Growth Dinner · Fort Eisenhower', region: 'fort',
    text: '"Will you remove the state pension fund from asset managers that use ESG standards? The Treasurer estimates the change will cost $180 million in fees and lower returns."',
    answers: [
      { text: 'Yes. Our pensions will not fund woke capital.',
        fx: { maga: 3, liberty: -2, chamber: -4, seniors: -2 },
        fb: 'A popular position with the base. Retirees and public employees worry about the cost.' },
      { text: 'Yes, and ban those firms from all state contracts.',
        fx: { maga: 2, online: 2 },
        fb: 'Texas and West Virginia have similar laws. It shows strength against Wall Street.' },
      { text: 'Pension returns must come before politics.',
        fx: { chamber: 4, seniors: 2, rino: 2, maga: -3 },
        fb: 'Financially responsible. Dunmore will say you protect BlackRock.' },
      { text: 'Move part of the pension into Bitcoin as a hedge.',
        fx: { liberty: 4, online: 4, seniors: -5, flag: 'btc' },
        fb: 'Crypto supporters are excited. Retirees are alarmed by the risk.' },
    ] },
  { id: 'btc_crash', cond: s => has(s, 'btc'), priority: true,
    setting: 'State Treasurer\'s Office',
    text: 'Bitcoin has fallen 40%. The pension fund has lost $900 million on paper. The Treasurer asks how you will explain it to retirees.',
    answers: [
      { text: 'This is a long-term investment. We will not sell at the bottom.',
        fx: { online: 3, liberty: 2, seniors: -5 },
        fb: 'Crypto supporters agree. Retirees see the loss, not the strategy.' },
      { text: 'Federal monetary policy caused this. It proves why we need hard assets.',
        fx: { liberty: 3, maga: 2, seniors: -2 },
        fb: 'This moves the blame. The loss is still on your record.' },
      { text: 'We will exit the position and restore traditional investments.',
        fx: { seniors: 2, liberty: -3, rino: 1 },
        fb: 'This limits the damage. It also confirms that the decision was a mistake.' },
    ] },
  { id: 'fluoride', setting: 'Health Freedom Rally · Osgood', region: 'osgood',
    text: 'The organizer asks: "Will you ban fluoride from public drinking water, as Utah and Florida did?"',
    answers: [
      { text: 'Yes. Statewide.',
        fx: { maga: 3, online: 3, seniors: -2 },
        fb: 'The health-freedom movement is now a large part of the base. Dentists warn about the effects on children.' },
      { text: 'Let each county decide.',
        fx: { liberty: 3, maga: 1 },
        fb: 'A local-control answer that most factions accept.' },
      { text: 'Ban it, and review all vaccine requirements in the state.',
        fx: { online: 4, maga: 2, seniors: -4 },
        fb: 'This adopts the MAHA agenda completely. Older voters and doctors are concerned.' },
      { text: 'The science supports fluoride. I will not ban it.',
        fx: { rino: 3, seniors: 2, maga: -4, online: -3 },
        fb: 'You have taken the establishment side on an issue the base cares about more than you think.' },
    ] },
  { id: 'sanctuary', setting: 'Interview · KCIM-TV Channel 4',
    text: '"The Lawrenceville city council has voted to limit cooperation with ICE. What will you do?"',
    answers: [
      { text: 'Send the National Guard to enforce state immigration law.',
        fx: { guns: 3, maga: 4, chamber: -2 },
        fb: 'A show of force the base wants. Local officials say it will escalate the conflict.' },
      { text: 'Withhold state funding until the city complies.',
        fx: { maga: 3, liberty: 1 },
        fb: 'An effective tool with little risk. Most factions accept it.' },
      { text: 'Charge the council members under the state anti-sanctuary law.',
        fx: { guns: 4, online: 4, maga: 3, chamber: -4, seniors: -2 },
        fb: 'This is the most aggressive option. It would make Cimarron the first state to prosecute local officials for this.' },
      { text: 'This is a local decision. I will not override it.',
        fx: { rino: 4, liberty: 2, maga: -6 },
        fb: 'Consistent with local control, but not in this primary. The base will not accept it on immigration.' },
    ] },
  { id: 'prayer', setting: 'Cornerstone Church · Caney Ridge', region: 'bible',
    text: 'A bill would require public schools to set aside time each day for prayer and Bible reading. Will you sign it?',
    answers: [
      { text: 'Yes.',
        fx: { faith: 4, liberty: -3 },
        fb: 'Evangelical leaders see this as a priority. It will almost certainly go to the Supreme Court.' },
      { text: 'Yes, and add state-funded chaplains in schools.',
        fx: { faith: 5, online: 2, liberty: -3, seniors: -1 },
        fb: 'Texas passed a chaplain law in 2023. This matches Pastor Rick\'s agenda.' },
      { text: 'A moment of silence, not required prayer.',
        fx: { rino: 1, faith: -1, seniors: 1 },
        fb: 'A careful legal position. Pastor Rick will say it is not enough.' },
      { text: 'Parents, not the state, should lead children in prayer.',
        fx: { liberty: 3, faith: -5 },
        fb: 'Libertarians agree. The church network will see it as opposition.' },
    ] },
  { id: 'machine_guns', setting: 'Gun Show · Harlan Fairgrounds', region: 'harlan',
    text: 'A bill would declare that firearms made and sold only in Cimarron are exempt from federal regulation. Will you sign it?',
    answers: [
      { text: 'Yes. Federal gun laws do not apply to goods that never cross state lines.',
        fx: { guns: 5, liberty: 3, chamber: -2, seniors: -2 },
        fb: 'Gun rights activists consider it a landmark. Federal courts have rejected similar laws before.' },
      { text: 'Yes, and direct state police not to assist the ATF.',
        fx: { guns: 4, online: 3, maga: 1, seniors: -2 },
        fb: 'This is an open challenge to federal authority. Krantz will say it was his idea.' },
      { text: 'Federal law still applies. I will not sign a law that I know is unconstitutional.',
        fx: { rino: 3, guns: -5, chamber: 1 },
        fb: 'Legally correct. Gun owners will hear that you chose Washington over them.' },
      { text: 'I support it, but we should wait for the Supreme Court case.',
        fx: { guns: 1, seniors: 1 },
        fb: 'This delays the question. Neither side is satisfied.' },
    ] },
  { id: 'snap', setting: 'Town Hall · Pratt Junction', region: 'pratt',
    text: '"What changes will you make to food assistance in Cimarron?"',
    answers: [
      { text: 'Require drug tests for all recipients.',
        fx: { maga: 2, seniors: 2, money: -.05 },
        fb: 'A popular idea with the base. Other states found that such programs cost more than they saved.' },
      { text: 'Add work requirements and time limits.',
        fx: { liberty: 3, maga: 2, seniors: 1 },
        fb: 'This is standard conservative policy. Most factions support it.' },
      { text: 'Ban the purchase of soda and candy with benefits.',
        fx: { maga: 2, online: 2, liberty: -3 },
        fb: 'This is part of the MAHA agenda and several states have done it. Libertarians call it the nanny state.' },
      { text: 'The program feeds children. I will not cut it.',
        fx: { rino: 3, seniors: 1, maga: -3, liberty: -2 },
        fb: 'A compassionate answer. It will be used against you as "defending welfare."' },
    ] },
  { id: 'homeless', setting: 'Downtown Business Alliance · Fort Eisenhower', region: 'fort',
    text: '"Homelessness in Fort Eisenhower has doubled in two years. What is your plan?"',
    answers: [
      { text: 'Ban public camping and enforce it with arrests.',
        fx: { guns: 3, maga: 2, chamber: 2 },
        fb: 'The Supreme Court allowed these bans in 2024. Businesses and law-and-order voters support it.' },
      { text: 'Require treatment for addiction and mental illness, including civil commitment.',
        fx: { seniors: 3, guns: 1, liberty: -2 },
        fb: 'This is a serious policy that many conservatives now support. Libertarians worry about civil liberties.' },
      { text: 'Fund a Housing First program.',
        fx: { rino: 4, maga: -4, chamber: 1 },
        fb: 'Many conservatives consider Housing First a failed progressive model. This is a costly position in the primary.' },
      { text: 'Partner with churches and faith-based shelters instead of government programs.',
        fx: { faith: 4, liberty: 2 },
        fb: 'This appeals to both evangelicals and small-government voters.' },
    ] },
  { id: 'covid', setting: 'Patriot Radio 1340 AM',
    text: '"Should state officials who enforced COVID lockdowns and mandates be held accountable?"',
    answers: [
      { text: 'Yes. They should be removed from state employment.',
        fx: { maga: 3, online: 2, chamber: -2 },
        fb: 'A popular answer. It would remove many experienced public health staff.' },
      { text: 'Yes. We need a state commission with subpoena power.',
        fx: { online: 5, maga: 2, seniors: -3 },
        fb: 'This is what the New Right wants. Older voters are worried it will become a political trial.' },
      { text: 'We should learn from it and move forward.',
        fx: { rino: 3, maga: -4 },
        fb: 'The base does not want to move forward. It wants accountability.' },
      { text: 'Pass a law that bans all future vaccine and mask mandates.',
        fx: { maga: 3, liberty: 2 },
        fb: 'This looks forward and satisfies most of the coalition.' },
    ] },
  { id: 'aquifer', setting: 'Water Board Hearing · The Panhandle', region: 'panhandle',
    text: '"The aquifer under the Panhandle will run dry in about 25 years at current use. Hydrologists recommend a 15% cut in pumping. What will you do?"',
    answers: [
      { text: 'Water rights belong to the farmers. There will be no mandatory cuts.',
        fx: { farm: 4, liberty: 2 },
        fb: 'Farmers support you now. The long-term problem remains.' },
      { text: 'Mandatory 15% cuts, with compensation for farmers.',
        fx: { rino: 2, farm: -6, liberty: -2, money: -.05 },
        fb: 'Scientists support it. Farmers see it as the state taking their water.' },
      { text: 'Voluntary conservation with state incentives.',
        fx: { farm: 2, chamber: 1 },
        fb: 'A reasonable approach. Experts say voluntary programs have not worked in the past.' },
      { text: 'The crisis is exaggerated by environmental groups.',
        fx: { maga: 3, farm: -1 },
        fb: 'The base agrees. Some farmers have already seen their wells go dry.' },
    ] },
  { id: 'crypto', setting: 'Crypto Conference · Pratt Junction', region: 'pratt',
    text: '"Will you create a state Bitcoin reserve and accept crypto for state payments?"',
    answers: [
      { text: 'Yes. Cimarron will be the most crypto-friendly state in America.',
        fx: { liberty: 5, online: 4, seniors: -3, chamber: -2 },
        fb: 'Vaskel\'s supporters notice. Older voters see it as speculation with public money.' },
      { text: 'Accept crypto for payments, but no public investment.',
        fx: { liberty: 2, online: 2 },
        fb: 'A limited step that few voters object to.' },
      { text: 'Make gold and silver legal tender instead.',
        fx: { liberty: 3, seniors: 3, maga: 2 },
        fb: 'Several states have passed similar laws. Hard-money conservatives support it.' },
      { text: 'No. The state should not speculate with public money.',
        fx: { seniors: 2, liberty: -4, online: -2 },
        fb: 'Fiscally careful. Vaskel will say you do not understand the future.' },
    ] },
  { id: 'secede', setting: 'Rally · Harlan County Courthouse', region: 'harlan',
    text: 'A petition with 60,000 signatures asks the legislature to call for a Convention of States. A smaller group wants a vote on whether Cimarron should leave the Union. Where do you stand?',
    answers: [
      { text: 'I support a Convention of States to limit federal power.',
        fx: { liberty: 3, maga: 2, seniors: 2 },
        fb: 'This is a mainstream conservative position with wide support.' },
      { text: 'Cimarron should have the right to decide its future, including independence.',
        fx: { online: 5, guns: 3, seniors: -5, chamber: -5 },
        fb: 'A small but committed group supports this. Most voters, especially older ones, do not.' },
      { text: 'Cimarron should refuse to follow unconstitutional federal laws.',
        fx: { online: 3, guns: 3, maga: 2 },
        fb: 'Nullification is a strong message to the most active part of the base.' },
      { text: 'We are Americans. I will not entertain secession talk.',
        fx: { seniors: 3, rino: 1, online: -3 },
        fb: 'Older voters appreciate it. Some activists see it as disloyalty to the state.' },
    ] },
  { id: 'pledge', setting: 'Taxpayers Association Luncheon · Fort Eisenhower', region: 'fort',
    text: 'The Taxpayers Association asks you to sign its pledge never to raise any tax or fee.',
    answers: [
      { text: 'Sign it, and promise to cut the sales tax next.',
        fx: { liberty: 4, chamber: 2, maga: 1 },
        fb: 'This earns you the Association\'s endorsement and its donors.' },
      { text: 'Sign it.',
        fx: { liberty: 3 },
        fb: 'Expected. It limits your options if the budget deficit grows.' },
      { text: 'I do not sign pledges. My record speaks for itself.',
        fx: { liberty: -5, rino: 2 },
        fb: 'The Association will run ads saying you "refused to rule out tax increases."' },
      { text: 'Sign it, and add a pledge to reduce state spending every year.',
        fx: { liberty: 3, maga: 1, online: 1 },
        fb: 'This goes beyond what they asked. Fiscal conservatives are impressed.' },
    ] },
  { id: 'farmland', setting: 'Farm Bureau Convention · Sumner Valley', region: 'sumner',
    text: '"Should Cimarron ban citizens and companies from China and other adversary nations from owning farmland?"',
    answers: [
      { text: 'Yes, and force them to sell what they already own.',
        fx: { maga: 4, farm: 3, online: 2, chamber: -2 },
        fb: 'This is popular across the coalition. Business groups worry about foreign investment in general.' },
      { text: 'Yes, for new purchases.',
        fx: { maga: 2, farm: 2 },
        fb: 'A common position that more than 20 states have taken.' },
      { text: 'Ban all foreign ownership of farmland, from any country.',
        fx: { farm: 3, online: 3, chamber: -4 },
        fb: 'This would affect investors from allied countries too. Farmers who want to sell land are concerned.' },
      { text: 'Current federal review is enough.',
        fx: { rino: 3, chamber: 2, maga: -4, farm: -2 },
        fb: 'Few voters believe this. It is a costly answer.' },
    ] },
  { id: 'pipeline', setting: 'Landowners Meeting · The Panhandle', region: 'panhandle',
    text: 'A company wants to use eminent domain to build a carbon dioxide pipeline across 200 farms. Business groups support it. Landowners are angry.',
    answers: [
      { text: 'No eminent domain for private pipelines. Property rights come first.',
        fx: { farm: 5, liberty: 4, maga: 2, chamber: -4 },
        fb: 'This is the position that has united farmers and populists in Iowa and the Dakotas.' },
      { text: 'The project creates jobs. Landowners should be paid fairly.',
        fx: { chamber: 4, rino: 2, farm: -5, liberty: -2 },
        fb: 'Business groups are pleased. Landowners feel abandoned.' },
      { text: 'Carbon capture is a climate scam. Stop the project.',
        fx: { maga: 4, online: 2, farm: 3, chamber: -3 },
        fb: 'This combines property rights with climate skepticism. It is popular with the base.' },
      { text: 'Let the Public Utilities Commission decide.',
        fx: { rino: 1 },
        fb: 'You have avoided the question. Landowners wanted to know where you stand.' },
    ] },
  { id: 'vouchers', setting: 'School Choice Rally · Osgood', region: 'osgood',
    text: '"Will you sign a universal school voucher program? Rural Republicans say it would take money from their public schools."',
    answers: [
      { text: 'Yes. Universal school choice for every family.',
        fx: { liberty: 4, faith: 4, online: 2, farm: -3 },
        fb: 'This is a top priority for conservative donors and religious schools. Rural voters, whose public school is often the largest employer, are worried.' },
      { text: 'Yes, but guarantee that rural school funding will not fall.',
        fx: { liberty: 2, faith: 2, farm: 1, money: -.05 },
        fb: 'This is how Texas passed its program. It is expensive, but it keeps the coalition together.' },
      { text: 'Only for families in failing school districts.',
        fx: { rino: 2, chamber: 1, faith: -2, liberty: -2 },
        fb: 'This is the old compromise. School choice activists now consider it too little.' },
      { text: 'Yes, and require all public schools to post their curriculum online.',
        fx: { faith: 3, online: 3, liberty: 2, farm: -2 },
        fb: 'This combines school choice with parents\' rights. It is strongly supported by activists.' },
    ] },
  { id: 'everify', setting: 'Builders Association · Fort Eisenhower', region: 'fort',
    text: '"Dunmore wants to require every employer in the state to use E-Verify. Do you support it?"',
    answers: [
      { text: 'Every employer, with serious penalties.',
        fx: { maga: 4, online: 2, chamber: -5, farm: -4 },
        fb: 'A strong enforcement position. Builders and farmers say they cannot find legal workers.' },
      { text: 'For all employers except agriculture.',
        fx: { chamber: 2, farm: 3, maga: 1 },
        fb: 'A common compromise. Dunmore will say it has "a hole big enough for a tractor."' },
      { text: 'Only for state contractors.',
        fx: { chamber: 3, rino: 2, maga: -3 },
        fb: 'This is the current law in several states. It will be seen as weak.' },
      { text: 'Yes, and make it a state crime to hire illegal workers.',
        fx: { maga: 5, guns: 2, chamber: -5, farm: -3 },
        fb: 'The strongest option available. Business donors will take their money elsewhere.' },
    ] },
  { id: 'busing', setting: 'Border Security Roundtable · Capitol',
    text: '"The Governor of Texas asks other Republican states to send National Guard troops to the southern border. Will Cimarron send troops?"',
    answers: [
      { text: 'Yes. 500 Guard members, paid for by the state.',
        fx: { guns: 3, maga: 4, pres: 3, money: -.1 },
        fb: 'A visible commitment to the border. It costs the state money, and some families object to long deployments.' },
      { text: 'Yes, but Washington should pay for it.',
        fx: { maga: 2, liberty: 1 },
        fb: 'A reasonable condition. It looks less committed.' },
      { text: 'Yes, and send state police to support ICE operations here too.',
        fx: { maga: 4, guns: 2, online: 2, farm: -2 },
        fb: 'The strongest position. Agricultural employers are concerned about enforcement at home.' },
      { text: 'Our Guard is needed here in Cimarron.',
        fx: { rino: 3, maga: -5 },
        fb: 'Practical, but the base sees the border as the most important issue in the country.' },
    ] },
  { id: 'ivf', setting: 'Interview · Cimarron Ledger',
    text: '"The state Supreme Court has ruled that frozen embryos are legal persons. Two fertility clinics have stopped IVF services. Do you support the ruling?"',
    answers: [
      { text: 'Life begins at conception. I support the ruling.',
        fx: { faith: 5, online: 2, seniors: -3, farm: -2 },
        fb: 'The most consistent pro-life position. Many Republican families who used IVF are upset.' },
      { text: 'I support the ruling, and I will sign a law to protect IVF.',
        fx: { maga: 1, seniors: 1 },
        fb: 'Alabama took this path. It satisfies most voters, but pro-life activists see a contradiction.' },
      { text: 'IVF helps families. I will protect it.',
        fx: { rino: 3, seniors: 3, faith: -5 },
        fb: 'Popular with the general public. Pastor Rick will call it a betrayal of the pro-life cause.' },
      { text: 'This is a matter for the courts.',
        fx: { rino: 1 },
        fb: 'This avoids the question. Both sides wanted an answer.' },
    ] },
  { id: 'dei_state', setting: 'Cabinet Meeting · Capitol',
    text: 'Your staff report that several state agencies still run diversity training programs under new names. What do you order?',
    answers: [
      { text: 'End all such programs and fire the staff who run them.',
        fx: { maga: 3, online: 2 },
        fb: 'A clear action the base will reward.' },
      { text: 'End the programs and require loyalty to state policy in agency hiring.',
        fx: { online: 5, maga: 1, seniors: -1, chamber: -2 },
        fb: 'This is the New Right approach: control of the bureaucracy. Critics say it politicizes the civil service.' },
      { text: 'Review the programs and keep those that are required by federal law.',
        fx: { chamber: 2, rino: 2, maga: -2 },
        fb: 'Legally cautious. It will be reported as "Governor keeps DEI."' },
      { text: 'Replace them with training on the Constitution.',
        fx: { maga: 2, seniors: 2, faith: 1 },
        fb: 'A positive replacement that most factions welcome.' },
    ] },
  { id: 'national_guard_city', setting: 'Interview · Fox News',
    text: '"The President has sent federal troops into several cities to fight crime. Would you use the National Guard in Fort Eisenhower?"',
    answers: [
      { text: 'Yes. Crime in our capital is unacceptable.',
        fx: { maga: 4, guns: 3, pres: 4, chamber: -3, seniors: -1 },
        fb: 'This aligns you with the President. City leaders, including Republicans, say the crime numbers do not justify it.' },
      { text: 'I would support the President sending federal forces if he chooses.',
        fx: { maga: 3, pres: 3 },
        fb: 'Loyal, without committing state forces.' },
      { text: 'Our police can handle it. We will give them more funding.',
        fx: { rino: 2, seniors: 2, guns: 2, maga: -2 },
        fb: 'A law-and-order answer without the Guard. The base wanted more.' },
      { text: 'Only if local officials request it.',
        fx: { rino: 3, liberty: 2, maga: -4 },
        fb: 'The host will describe this as "waiting for permission."' },
    ] },
  { id: 'porn', setting: 'Family Policy Council Radio · Caney Ridge', region: 'bible',
    text: '"Some conservatives want the state to ban online pornography completely. The Liberty Caucus opposes it. Where do you stand?"',
    answers: [
      { text: 'Ban it. It harms families and children.',
        fx: { faith: 5, online: 1, liberty: -5 },
        fb: 'Social conservatives and the New Right support this. Enforcement would require wide internet controls.' },
      { text: 'Require strict age verification, but no total ban.',
        fx: { faith: 2, seniors: 1, liberty: -1 },
        fb: 'This is the approach the Supreme Court upheld in 2025. It is broadly acceptable.' },
      { text: 'Adults have the right to make their own choices.',
        fx: { liberty: 4, faith: -5, rino: 1 },
        fb: 'A principled libertarian position. Evangelical voters will not forget it.' },
      { text: 'Let parents use filters. The state should focus on other issues.',
        fx: { liberty: 1, faith: -2 },
        fb: 'This avoids the fight. Neither side is satisfied.' },
    ] },
  { id: 'podcast_guest', cond: s => has(s, 'podcast'), priority: true,
    setting: 'Recording Studio · Your Weekly Show',
    text: 'A guest on your show says the Federal Reserve and "globalist bankers" are secretly controlling the economy. Your staff know this language has antisemitic associations. How do you respond on air?',
    answers: [
      { text: 'Let him continue. We are here to have open conversations.',
        fx: { online: 4, seniors: -2, chamber: -2 },
        fb: 'The episode performs well online. Several Jewish and pro-Israel Republican leaders call your office.' },
      { text: 'Change the subject.',
        fx: { maga: 1 },
        fb: 'You have avoided the moment. Critics will say you did not challenge him.' },
      { text: 'Push back: "That language has an ugly history, and it has no place on this show."',
        fx: { seniors: 3, faith: 2, online: -3 },
        fb: 'Many conservatives respect it. Part of the online right calls you "controlled."' },
    ] },
  { id: 'pardon_repeat', cond: s => has(s, 'pardons'), priority: true,
    setting: 'Press Conference · Capitol',
    text: '"One of the men you pardoned was arrested again. He threatened a county clerk who certified an election. What is your comment?"',
    answers: [
      { text: 'He deserves due process. I will not comment further.',
        fx: { maga: 2, seniors: -2 },
        fb: 'This avoids condemning him. County clerks, many of them Republicans, notice.' },
      { text: 'Threatening election officials is a crime. He will face the law.',
        fx: { rino: 2, seniors: 3, maga: -3 },
        fb: 'A clear law-and-order answer. Dunmore\'s supporters say you have turned on the pardoned protesters.' },
      { text: 'The clerk certified a questionable election. People are angry, and I understand why.',
        fx: { maga: 3, online: 3, seniors: -3, chamber: -2 },
        fb: 'The base agrees. Clerks across the state ask for police protection.' },
    ] },
  { id: 'child_labor_followup', cond: s => has(s, 'child_labor'), priority: true,
    setting: 'Interview · KCIM-TV Channel 4',
    text: '"A 15-year-old was seriously injured on a night shift at the Garnett plant. His family says he was working 40 hours a week during the school year. Will you change the law?"',
    answers: [
      { text: 'No. Work builds character. This was a workplace accident.',
        fx: { chamber: 3, liberty: 2, faith: -2, seniors: -3 },
        fb: 'Employers are relieved. Parents across the state are not.' },
      { text: 'We will limit hours during the school year, but keep the reform.',
        fx: { seniors: 2, faith: 1, rino: 1 },
        fb: 'A responsible correction. It admits the law went too far.' },
      { text: 'The plant is responsible. The state will investigate.',
        fx: { maga: 1, seniors: 1, chamber: -2 },
        fb: 'This moves the blame to the employer. Reporters will ask who signed the law.' },
    ] },
  { id: 'red_flag', setting: 'Mothers\' March · Fort Eisenhower', region: 'fort',
    text: 'After a school shooting in a neighboring state, a group of Republican mothers asks you to support a "red flag" law that lets courts remove guns from dangerous people.',
    answers: [
      { text: 'No. Red flag laws violate due process and the Second Amendment.',
        fx: { guns: 4, liberty: 3, maga: 2 },
        fb: 'This is the position of every gun rights group in the state.' },
      { text: 'No. I will sign a law that bans red flag orders in Cimarron.',
        fx: { guns: 5, liberty: 2, maga: 2, seniors: -1 },
        fb: 'Several states have done this. It is the strongest pro-gun position available.' },
      { text: 'I will consider a narrow law with strong due process.',
        fx: { rino: 4, seniors: 2, guns: -6 },
        fb: 'The mothers appreciate it. The Rifle Association will call it "gun confiscation."' },
      { text: 'The answer is armed security in schools and better mental health care.',
        fx: { guns: 2, seniors: 2, faith: 1 },
        fb: 'A familiar answer that holds the coalition together.' },
    ] },
  { id: 'medicaid', setting: 'Rural Hospital Association · The Panhandle', region: 'panhandle',
    text: '"Three rural hospitals may close without more Medicaid funding. Will you expand Medicaid, as voters in some red states have?"',
    answers: [
      { text: 'No. Medicaid expansion is Obamacare.',
        fx: { maga: 3, liberty: 3, seniors: -2, farm: -2 },
        fb: 'Consistent with the party line. The hospitals serve many older and rural voters.' },
      { text: 'No, but the state will give emergency grants to rural hospitals.',
        fx: { farm: 2, seniors: 2, liberty: -1, money: -.05 },
        fb: 'This protects rural voters without expansion. Budget hawks ask where the money comes from.' },
      { text: 'Expand it, with strict work requirements.',
        fx: { rino: 4, seniors: 3, farm: 2, maga: -4, liberty: -3 },
        fb: 'The hospital association supports it. In this primary, "expansion" is the only word that matters.' },
      { text: 'Replace Medicaid with health savings accounts.',
        fx: { liberty: 4, chamber: 1, seniors: -2 },
        fb: 'A free-market proposal. Hospital leaders say it will not keep their doors open.' },
    ] },
  { id: 'ukraine', setting: 'Interview · Newsmax',
    text: '"Should the United States continue to send aid to Ukraine?"',
    answers: [
      { text: 'No. Not one more dollar. America first.',
        fx: { maga: 4, online: 3, seniors: -1, chamber: -2 },
        fb: 'This is the majority view among primary voters. A few older conservatives disagree.' },
      { text: 'Europe should pay for its own defense.',
        fx: { maga: 2, liberty: 2 },
        fb: 'A popular framing that avoids the details.' },
      { text: 'Stopping Russia is in America\'s interest. We should support Ukraine.',
        fx: { rino: 3, seniors: 2, chamber: 2, maga: -6, pres: -3 },
        fb: 'This is the Reagan position. It is now a minority position in this primary.' },
      { text: 'That is a federal issue. I am focused on Cimarron.',
        fx: { rino: 1 },
        fb: 'This avoids the question. The host presses you twice.' },
    ] },
];


// ---------- Opponent news (campaign wire) ----------
// fx: faction deltas for that opponent.
const NEWS = {
  dunmore: [
    ['Dunmore releases a video that accuses you of "governing like a Democrat." It has 2 million views.', { maga: 1, online: 1 }],
    ['Dunmore draws 5,000 people to a rally in Osgood and promises "mass deportation on day one."', { maga: 2, online: 1 }],
    ['Dunmore unveils a plan to end state income-tax withholding for workers who refuse federal "digital ID."', { online: 2, liberty: 1 }],
    ['Dunmore is endorsed by a national populist PAC with $3 million to spend in the state.', { maga: 2 }],
    ['Dunmore says that he would appoint his podcast producer as Chief of Staff. Older voters react poorly.', { online: 1, seniors: -2 }],
    ['Reporters find that Dunmore\'s campaign merchandise is manufactured in Vietnam.', { maga: -2 }],
    ['Dunmore accuses the Ledger of "election interference" after a critical article.', { online: 1, seniors: -1 }],
    ['Dunmore challenges you to a one-on-one debate on his podcast.', { online: 2 }],
    ['A former aide says Dunmore missed 70% of his official duties as Lieutenant Governor.', { seniors: -2, chamber: -1 }],
  ],
  rick: [
    ['Pastor Rick\'s church network registers 12,000 new voters in Caney Ridge.', { faith: 2 }],
    ['Pastor Rick promises to "put God back in every public institution in Cimarron."', { faith: 2, liberty: -1 }],
    ['Pastor Rick holds a statewide prayer rally at the Capitol. Attendance: 8,000.', { faith: 2, seniors: 1 }],
    ['Reporters question the use of the church\'s private jet for trips to Mexico.', { faith: -2, maga: -1 }],
    ['Pastor Rick proposes closing businesses on Sundays. Retail groups object.', { faith: 2, chamber: -2 }],
    ['Pastor Rick is endorsed by 400 pastors across the state.', { faith: 2, seniors: 1 }],
    ['Pastor Rick says that "a vote for the Governor is a vote for compromise with evil."', { faith: 1, chamber: -1 }],
  ],
  krantz: [
    ['Sheriff Krantz arrests a county commissioner on corruption charges.', { guns: 2, seniors: 1 }],
    ['Krantz rides at the front of a 1,000-truck "Freedom Convoy" to the Capitol.', { guns: 1, farm: 1 }],
    ['Krantz says he will "enforce the Constitution as the Founders intended."', { guns: 1 }],
    ['Krantz deputizes 400 volunteers into a reserve posse for border and immigration operations.', { guns: 2, maga: 1 }],
    ['Krantz declines to appear on Dunmore\'s podcast, calling it "entertainment."', { seniors: 1, online: -1 }],
    ['Krantz promises to audit the Federal Reserve\'s dealings with state banks.', { liberty: 2 }],
    ['Krantz is endorsed by the state Constitutional Sheriffs Association.', { guns: 2 }],
  ],
  vaskel: [
    ['Vaskel\'s super PAC spends $4 million on television ads in one week.', { liberty: 1, maga: 1 }],
    ['Vaskel promises to replace state agencies with "AI-first" digital services.', { liberty: 2, seniors: -1 }],
    ['Vaskel posts more than 100 times in one day. Most of the posts attack you.', { online: 2 }],
    ['Vaskel hosts a "Network State" conference. Few Cimarron residents attend.', { online: 1, farm: -1 }],
    ['Vaskel offers to pay the legal fees of any parent who sues a school district.', { liberty: 1, faith: 1 }],
    ['In an interview, Vaskel cannot name the largest crop grown in Cimarron.', { farm: -2, seniors: -1 }],
    ['Vaskel pledges to make Cimarron "the Singapore of the Plains."', { chamber: 1 }],
    ['Vaskel buys a controlling stake in the state\'s largest newspaper.', { chamber: 1, seniors: -1 }],
  ],
  whitlock: [
    ['Whitlock releases a 90-page policy plan on water, roads and rural hospitals.', {}],
    ['Whitlock calls for "a return to civility." Protesters interrupt her event.', {}],
    ['Whitlock is endorsed by two former Republican governors.', { chamber: 1, maga: -1 }],
    ['Whitlock says the party "has confused anger with principle."', {}],
    ['Whitlock holds a town hall in Lake Cheney. About 50 people attend.', { seniors: 1 }],
  ],
};

