// ============================================================
// ADVICE — what each candidate's own staff says in the shared events.
// ADVICE_FOR[candidate][eventId] replaces the event's advice (which is written for the Governor's staff).
// Roles: wade = campaign manager, dana = pollster, tom = faith outreach, kyle = digital, pryce = chief of staff.
// ============================================================

const ADVICE_FOR = {
  // Travis Dunmore: Tanner Hoyt (producer), Roz Kemp (pollster), Pastor Dale Ingram, Zach Orr (clips), Marcy Dunmore (wife).
  dunmore: {
    church_arrest: [['wade', 'Your audience wants you to defend the arrest. Half your callers tonight will say "no exceptions."'], ['tom', 'Travis, I have preached in that church. If you mock it, you lose the pastors you still have.'], ['kyle', 'The video of the crying children is everywhere. Whatever you say, say it on the show first.']],
    tornado: [['wade', 'Take the show to Sumner. Three days live. Nobody else can do that.'], ['pryce', 'Travis, go as a man, not as a host. Leave the microphone in the truck for one day.'], ['dana', 'Voters are watching the Governor. If he is slow, they will notice who was there.']],
    hospital: [['dana', 'These are your voters, Travis. Rural, angry, and tired of being ignored.'], ['wade', 'Blame Washington and the hospital chains. That is a segment that writes itself.'], ['pryce', 'Whatever you say about Medicaid, the Chamber will clip it.']],
    donor_wife: [['kyle', 'The accounts attacking her are our audience. If you condemn them by name, the comments will turn on you tonight.'], ['tom', 'Racism is a sin, Travis. Pastors will say it on Sunday whether you do or not.'], ['pryce', 'Say it once, on the show, and move on. Do not let it become the show.']],
    shooting: [['wade', 'Gun owners are half your audience. Do not give an inch.'], ['tom', 'Go to the vigil. No cameras. Just go.'], ['dana', 'Mothers in Osgood want to hear that you care about their kids more than about the Rifle Association.']],
    lawrenceville_murder: [['wade', 'This is the story the show was built for. But the family asked not to be used.'], ['tom', 'Call her father before you say one word on air.'], ['kyle', 'Every clip you make tonight will be shared a million times. Make sure you can live with it.']],
    rifle_q: [['wade', 'Krantz owns this endorsement unless you take it from him.'], ['dana', 'Background checks on private sales are popular even with your listeners.']],
    right_to_life: [['tom', 'Pastor Rick has this endorsement unless you take the pledge.'], ['dana', 'Women in your audience are split on exceptions. Do not assume they agree with you.']],
    farm_bureau: [['dana', 'Farmers do not listen to podcasts. They vote anyway.'], ['wade', 'An immigration exemption for farms is amnesty with a tractor. You said that on air last year.']],
    youth_summit: [['kyle', 'This is your crowd, Travis. They know every clip. They want a yes.'], ['pryce', 'That theory will follow you to any office above this one. Think about 2034.'], ['dana', 'Older voters will hear a yes on the evening news.']],
    president_call: [['wade', 'The endorsement is the whole race. He likes you already. Close the deal.'], ['pryce', 'Firing the Secretary of State is a promise you will have to keep.'], ['dana', 'Potash tariffs hit farmers, and farmers are where you are weakest.']],
    favor_pardon: [['wade', 'The President remembers loyalty, and you have given him plenty. This seals it.'], ['dana', 'The victims are Panhandle farm families. Those are your callers.'], ['pryce', 'A pardon promise for a rich man who stole from farmers is not an America First story.']],
    favor_drones: [['wade', 'The son is the fastest way to his father.'], ['kyle', 'The Liberty Caucus will call it cronyism. Our audience will not care.'], ['pryce', 'We attack the Chamber for exactly this kind of deal, Travis.']],
    mideast_war: [['wade', 'The base will rally to the President, and your audience is the base.'], ['kyle', 'Half the chat is anti-war. The New Right thinks the President betrayed them.'], ['dana', 'Gas prices will decide this. Whoever stands closest to the President will pay.']],
    oil_shock: [['dana', 'Your listeners are paying $6.80. The calls are angry.'], ['wade', 'Do not abandon the President. Blame the generals if you have to blame someone.'], ['pryce', 'Talk about diesel. The farmers are listening now.']],
    fbi_krantz: [['wade', 'Defend Bo. Your audience hates the FBI more than they like you.'], ['dana', 'Gun owners will rally to Krantz. You cannot be on the other side.'], ['pryce', 'A man died in that jail. Do not make it a segment.']],
    krantz_standoff: [['wade', 'The ranchers are your audience. Stand with them.'], ['pryce', 'As Lieutenant Governor, you are in the chain of command. If someone dies, you were on that chain.'], ['dana', 'Voters oppose the BLM. They do not want a war.']],
    donor_deal: [['pryce', 'Voigt\'s money comes with a veto attached. You spent four years attacking this kind of deal.'], ['wade', 'Three million dollars is a lot of airtime.'], ['dana', 'Panhandle farmers care about those wells.']],
    straw_poll: [['wade', 'This room is your room. Delegates are activists.'], ['dana', 'Do not confuse the convention with the primary. The delegates love you. The voters are older.']],
    white_house_trip: [['wade', 'Four nights on Air Force One. The show basically produces itself.'], ['dana', 'Cimarron voters notice when you are not in Cimarron.'], ['pryce', 'The Governor will be here every day while you are gone.']],
    coburn_dui: [['wade', 'Do not go after a football hero. Your audience loves him.'], ['kyle', 'Ask who dismissed the case. Let the audience do the rest.']],
  },
  // Pastor Rick: Josh Dollins (his son), Beth Carraway (pollster), Elder Ray Sutton (Council), Kaylee Morrow (media), Deb Farris (treasurer).
  rick: {
    church_arrest: [['tom', 'Dad, Rev. Ortega has preached in our pulpit. The pastors are watching what you say about his church.'], ['wade', 'Border hawks in our congregation want you to defend the troopers. You cannot please both sides.'], ['dana', 'Evangelicals are split. Older church members lean toward sanctuary.']],
    tornado: [['wade', 'Cornerstone Relief can be in Sumner by morning. We have done this before.'], ['tom', 'The pastors in Sumner will open their churches as shelters. They are waiting for your call.'], ['pryce', 'Keep the church relief and the campaign separate. Reporters will look for the campaign logo on the trucks.']],
    hospital: [['tom', 'Her husband is a deacon at First Baptist in Dry Fork. The whole town knows him, and so do I.'], ['dana', 'Rural voters are angry, and many of them are in our churches.'], ['wade', 'Preach about it before you promise anything about Medicaid.']],
    donor_wife: [['tom', 'This is a sin, and every pastor in the state knows it. You should be the first to say so.'], ['kyle', 'Some of the accounts use Bible verses in their names. It is ugly.'], ['pryce', 'The Hales give to the church too, Dad.']],
    shooting: [['tom', 'It was a Christian school. Families first. Pray with them before anything else.'], ['wade', 'The Rifle Association is watching. Gun owners are in every pew.'], ['dana', 'Mothers want to hear that faith and safety go together.']],
    lawrenceville_murder: [['tom', 'The Carters attend a Baptist church in Lawrenceville. Call their pastor first.'], ['wade', 'Dunmore will hold a rally tonight. You can hold a vigil.'], ['dana', 'Older voters want justice. They also want dignity.']],
    rifle_q: [['wade', 'Krantz owns this endorsement. You can compete for it, but it will cost you something.'], ['dana', 'Background checks on private sales are popular with older churchgoers.']],
    right_to_life: [['tom', 'This endorsement should be ours already. The pro-life leaders expect you to take the pledge without blinking.'], ['dana', 'Women in our congregation are more divided on exceptions than the pulpit is.']],
    farm_bureau: [['dana', 'Farm families fill our churches in the Panhandle and Sumner Valley.'], ['wade', 'The immigration exemption will anger the border hawks in our congregation.']],
    youth_summit: [['kyle', 'Our youth ministry students are in that room. They want a yes.'], ['tom', 'That theory is not Christian, Dad. Every pastor on the Council will ask you about it.'], ['dana', 'Older churchgoers will be horrified by a yes.']],
    president_call: [['wade', 'The President has never been sure about you. This is your chance.'], ['pryce', 'Firing a public servant who did nothing wrong is not something you have ever done at Cornerstone.'], ['dana', 'Potash tariffs hurt the farm families in our churches.']],
    favor_pardon: [['tom', 'Several of those families are in our churches, Dad. I know their names.'], ['wade', 'This is how you get the President\'s endorsement.'], ['pryce', 'A promise to pardon a man who stole from farmers. Imagine that sermon.']],
    favor_drones: [['wade', 'The President\'s son can open doors nobody else can.'], ['pryce', 'Surveillance drones for the state police. The homeschool families will hate it.'], ['dana', 'Everyone hates no-bid contracts, including our members.']],
    mideast_war: [['tom', 'Our pastors will support the war. Many of them see it through their love for Israel.'], ['kyle', 'The young people in our church are against it. They say it on their phones, not in the pews.'], ['dana', 'If this lasts, gas prices will matter more than theology.']],
    oil_shock: [['dana', 'Church families are cutting back. The offering is down 12% this month.'], ['tom', 'Evangelicals still support the war. Nobody else does.'], ['pryce', 'Talk about diesel and the harvest. Farmers are praying for rain and for lower prices.']],
    fbi_krantz: [['wade', 'Gun owners in our churches will rally to Krantz.'], ['tom', 'A man died in that jail. Pray for his family before you say anything about the FBI.'], ['dana', 'Older voters want the truth, not a fight.']],
    krantz_standoff: [['tom', 'Pray for peace on that road, publicly. Nobody else will.'], ['wade', 'The ranchers are in our Panhandle churches.'], ['dana', 'Nobody wants an armed conflict on a county road.']],
    affair_rumor: [['tom', 'Go to church with your family this Sunday. For you, that is not a photo. It is just Sunday.'], ['wade', 'Every denial repeats the charge.'], ['pryce', 'Sue him. He has no evidence.']],
    donor_deal: [['pryce', 'Voigt wants a promise. You have never sold a promise from the pulpit.'], ['wade', 'Three million dollars would pay for a lot of vans.'], ['dana', 'The Panhandle farmers with leaking wells are in our churches.']],
    straw_poll: [['wade', 'Half of these delegates have been to Cornerstone.'], ['dana', 'The delegates are more religious than primary voters, which helps you.']],
    white_house_trip: [['wade', 'Four nights with the President. No pastor in America has done that during a campaign.'], ['tom', 'You will miss two Sundays at Cornerstone.'], ['dana', 'Voters notice when you are not here.']],
    coburn_dui: [['tom', 'Coburn has been divorced twice and arrested once. Our people have noticed without our help.'], ['wade', 'The President defended him. Be careful.']],
  },
  // Sheriff Krantz: Dale Voorhees (undersheriff), Norma Leeds (pollster), Chaplain Ed Birch, Tyler Stamm (posse), Carl Whitfield (lawyer).
  krantz: {
    church_arrest: [['wade', 'Bo, those were state troopers working with ICE. That is exactly the kind of federal cooperation you have fought.'], ['tom', 'A church is a church. I have been a chaplain for thirty years. You do not arrest men in the pews.'], ['dana', 'Evangelicals are split. Gun owners mostly back the arrest.']],
    tornado: [['wade', 'Our search-and-rescue team can be in Sumner in three hours.'], ['pryce', 'You are a sheriff, not the Governor. Help, and let the cameras find you.'], ['dana', 'Voters are watching how the Governor handles this. Your deputies are the contrast.']],
    hospital: [['dana', 'Rural voters are angry, and they are your voters.'], ['wade', 'Our deputies drive people to that hospital every week. Now they will drive them ninety minutes.'], ['pryce', 'Do not say "Medicaid." Say "rural hospitals."']],
    donor_wife: [['tom', 'This is wrong, Bo, and you have never been afraid to say something is wrong.'], ['kyle', 'Some of our posse volunteers are sharing these posts. We need to deal with that too.'], ['pryce', 'Say it once. You are a lawman. Threats are a crime.']],
    shooting: [['tom', 'Go to the vigil. A sheriff at a vigil means something.'], ['wade', 'The Rifle Association is with you. Any gun law ends that.'], ['dana', 'Mothers want to hear about armed officers in schools. That is your issue.']],
    lawrenceville_murder: [['wade', 'This is why you deputized the border posse, Bo.'], ['tom', 'Call the family first. You have made that call to families before.'], ['dana', 'Older voters trust sheriffs on crime more than anyone else.']],
    right_to_life: [['tom', 'Pro-life voters trust you, but they do not know you. This endorsement would introduce you.'], ['dana', 'Women in ranch country are divided on exceptions.']],
    farm_bureau: [['dana', 'Ranchers and farmers are your strongest group after gun owners.'], ['wade', 'The pipeline ban is your issue already. You stood against eminent domain in 2027.']],
    youth_summit: [['kyle', 'Young guys in the posse love this group. They want a yes.'], ['pryce', 'Bo, that theory is not a law-enforcement position. Do not make it yours.'], ['dana', 'Older voters trust you because you are serious. Keep it serious.']],
    president_call: [['wade', 'The President likes sheriffs. He likes you. Give him what he wants.'], ['pryce', 'The Secretary of State certified the election. You have never fired anyone for following the law.'], ['dana', 'Potash tariffs hit the ranchers who support you.']],
    favor_pardon: [['pryce', 'You have arrested men for less than what Renner did. A pardon promise would be quoted forever.'], ['wade', 'The President would owe you.'], ['dana', 'The victims are Panhandle ranch families. They are your voters.']],
    favor_drones: [['kyle', 'Drones for the state police? The posse will hate it. So will every rancher who values his privacy.'], ['wade', 'The son is the road to the President.'], ['pryce', 'You have spent your career fighting surveillance.']],
    mideast_war: [['wade', 'Gun owners and veterans will rally to the troops.'], ['kyle', 'The young guys in the posse are against another war. They say so at every meeting.'], ['dana', 'Gas prices will hit ranch country first.']],
    oil_shock: [['dana', 'Ranchers are paying $7.40 for diesel. They are angry.'], ['wade', 'Do not abandon the President in a war. The base will not forgive it.'], ['pryce', 'Talk about diesel, Bo. That is what they care about.']],
    affair_rumor: [['wade', 'You have been married 38 years, Bo. Say that, once.'], ['tom', 'Go to church with Marla and the grandkids. People in Harlan know you.'], ['pryce', 'Sue him. He has no evidence.']],
    donor_deal: [['pryce', 'Bo, a promise for money is a bribe in every county I know.'], ['wade', 'Three million dollars is a lot of television for a sheriff.'], ['dana', 'Ranchers with leaking wells are your voters.']],
    straw_poll: [['wade', 'The delegates want a fighter. You are the only one who has stood on a road for eleven days.'], ['dana', 'Delegates are more online than your voters.']],
    white_house_trip: [['wade', 'Four nights on the President\'s stage. For a county sheriff.'], ['dana', 'Harlan will notice you are gone.'], ['pryce', 'If something happens in the county while you are away, it is on you.']],
    coburn_dui: [['wade', 'You arrest drunk drivers for a living, Bo.'], ['kyle', 'Ask who dismissed the case. A sheriff has every right to ask.']],
    rifle_q: [['wade', 'The Rifle Association is already with us.']],
  },
  // Brent Vaskel: Nate Lindgren (COO), Sasha Imrie (data), Pastor Ben Otis (new hire), Devin Cho (growth), Margo Feld (counsel).
  vaskel: {
    church_arrest: [['tom', 'Brent, I know you do not go to church. The churches will notice what you say anyway.'], ['wade', 'Our meatpacking plants need those workers. The base wants the arrests. You cannot have both.'], ['dana', 'The data say evangelicals are split and older voters side with the church.']],
    tornado: [['wade', 'We can have satellite internet and drones in Sumner by tomorrow.'], ['pryce', 'Whatever you give, give it without your logo. The Governor\'s people will look for the logo.'], ['dana', 'Sumner Valley is where we are weakest. This is where they meet you.']],
    hospital: [['dana', 'Rural voters do not trust you yet. This is how they decide whether to.'], ['wade', 'We could fund telemedicine for every rural county. It works.'], ['pryce', 'Anything you pay for looks like buying votes during a campaign.']],
    donor_wife: [['pryce', 'Brent, half our engineers are Indian Americans. Your company is watching.'], ['kyle', 'The accounts attacking her are the New Right accounts that support us online.'], ['dana', 'Every group except the online right wants you to condemn it.']],
    shooting: [['tom', 'Go to the vigil. Do not bring a policy paper.'], ['wade', 'The Rifle Association does not trust you. Any gun law confirms their fears.'], ['dana', 'Suburban mothers want safety. They like technology answers more than you would think.']],
    lawrenceville_murder: [['wade', 'This is the immigration story every rival will use against your H-1B plans.'], ['tom', 'Call the family first. Please.'], ['dana', 'Older voters are moved by this more than any issue we have measured.']],
    rifle_q: [['wade', 'Gun owners do not trust a Californian. This questionnaire is how you change that.'], ['dana', 'Background checks are popular. The Rifle Association is not the electorate.']],
    right_to_life: [['tom', 'Brent, you have never said anything about abortion in public. This is your first time.'], ['dana', 'Our supporters in the Liberty Caucus are uneasy with no-exceptions pledges.']],
    farm_bureau: [['dana', 'Farmers are where we are weakest. This endorsement would change that.'], ['wade', 'The immigration exemption helps our plants too. Everyone will notice.']],
    youth_summit: [['kyle', 'This room is our base online. They want a yes.'], ['pryce', 'You employ 1,200 immigrants in Pratt Junction, Brent.'], ['dana', 'Donors and older voters will react badly to a yes.']],
    growth_club: [['pryce', 'The Club is your natural home, Brent. But their pledge would bind you as governor.'], ['wade', 'Their money plus yours means nobody else can keep up.']],
    president_call: [['wade', 'The President likes businessmen. Give him what he wants.'], ['pryce', 'Potash tariffs will hurt the farmers you are trying to win over.'], ['dana', 'The Secretary of State is popular with county clerks, and clerks talk.']],
    favor_pardon: [['pryce', 'Brent, a pardon promise for a man who cheated farmers is the Carpetbagger ad of the year.'], ['wade', 'The President rewards loyalty.'], ['dana', 'Farm families are the voters we most need.']],
    favor_drones: [['pryce', 'Our fund owns part of Liberty Drone. If you promise this contract, it is a conflict of interest in writing.'], ['wade', 'The son is the fastest way to the father.'], ['dana', 'The Liberty Caucus hates surveillance, and they are our base.']],
    mideast_war: [['wade', 'Markets are down 9%. Our portfolio is too.'], ['kyle', 'The New Right is anti-war, and they are our strongest group.'], ['dana', 'Gas prices will decide this.']],
    oil_shock: [['dana', 'Farmers and older voters are paying for this war. Speak to their costs.'], ['wade', 'Our data centers use a lot of power. Be careful talking about energy.'], ['pryce', 'Do not attack the President. Attack the price of diesel.']],
    fbi_krantz: [['wade', 'Gun owners will rally to Krantz. We do not have many of them to lose.'], ['pryce', 'A man died in that jail. Wait for the facts.'], ['dana', 'Older voters want the investigation to proceed.']],
    krantz_standoff: [['pryce', 'Armed men on a county road. This is exactly why investors worry about Cimarron.'], ['wade', 'The ranchers do not trust you. Stay careful.'], ['dana', 'Voters oppose the BLM. They do not want a war.']],
    affair_rumor: [['wade', 'Every denial repeats the charge.'], ['pryce', 'Sue him. We can afford the best lawyers in the country.'], ['tom', 'Go to church with your family, Brent. Any church.']],
    donor_deal: [['pryce', 'You do not need Voigt\'s money. Taking it looks like a deal between rich men.'], ['wade', 'Three million more would mean every market, every day.'], ['dana', 'Panhandle farmers already worry about your water plans.']],
    straw_poll: [['wade', 'Delegates want fire. You bring slides.'], ['dana', 'The delegates are online and religious. Half of that helps you.']],
    white_house_trip: [['wade', 'Four nights next to the President. The markets would love it.'], ['dana', 'Voters notice when you are not in Cimarron. You have only lived here four years.'], ['pryce', 'The President remembers who says yes.']],
    coburn_dui: [['wade', 'Do not attack a football hero. You are already the Californian.'], ['kyle', 'Ask who dismissed the case. Let others do the attacking.']],
  },
  // Carol Whitlock: Hal Brewer (manager), Joan Tillis (pollster), Rev. Arthur Pell (Methodist), Emma Sandoval (digital, 24), Peg Olsen (chief of staff).
  whitlock: {
    church_arrest: [['tom', 'Carol, you voted for the church-sanctuary resolution in 2011. Remind them.'], ['wade', 'The MAGA base will never vote for you anyway. Say what you believe.'], ['dana', 'Older voters lean toward the church. That is our electorate.']],
    tornado: [['pryce', 'Call the Appropriations chairman. You trained him. Relief can pass in three days.'], ['wade', 'Go to Sumner, and let people see someone who knows how government works.'], ['dana', 'Voters are watching the Governor. You can show them what competence looks like.']],
    hospital: [['dana', 'Rural voters are angry, and you are the only candidate with a plan for rural hospitals.'], ['wade', 'Your 90-page plan is finally useful.'], ['pryce', 'You supported Medicaid expansion with work requirements in 2019. They will find it anyway.']],
    donor_wife: [['tom', 'Carol, this is exactly why you are running. Say it plainly.'], ['kyle', 'The accounts attacking her are the same accounts that call you a RINO. You have nothing to lose.'], ['pryce', 'Richard Hale has given to your campaigns for twenty years.']],
    shooting: [['tom', 'Go to the vigil. Pray with them. You know how.'], ['dana', 'Suburban mothers are open to some action for a short time. They are our voters.'], ['wade', 'The Rifle Association has never endorsed you, and never will.']],
    lawrenceville_murder: [['tom', 'Call the family first.'], ['wade', 'Dunmore will be loud. Be serious.'], ['dana', 'Older voters want justice, and they want an adult.']],
    rifle_q: [['wade', 'You will not get this endorsement, Carol. The question is how to lose it well.'], ['dana', 'Background checks are popular with the voters we need.']],
    right_to_life: [['tom', 'You wrote the first heartbeat bill. Pro-life leaders have forgotten that.'], ['dana', 'Republican women over 50 oppose a no-exceptions pledge. They are our base.']],
    farm_bureau: [['dana', 'Farmers remember the Aquifer Compact. This endorsement is winnable.'], ['wade', 'The guest-worker exemption is your position anyway.']],
    youth_summit: [['kyle', 'I know this crowd. They will boo you whatever you say.'], ['pryce', 'Say no, clearly. It is who you are.'], ['dana', 'None of these voters will vote for you. Older voters will be watching.']],
    growth_club: [['pryce', 'The Club attacked you in 2016. They want a pledge you will never sign.'], ['wade', 'Their money would pay for the registration drive.']],
    president_call: [['pryce', 'The President has never liked you, Carol. There is no deal here.'], ['wade', 'Refuse politely. His voters were never ours.'], ['dana', 'Potash tariffs hurt the farmers who might vote for you.']],
    favor_pardon: [['pryce', 'Carol, you have never done a favor like this in thirty years.'], ['dana', 'The victims are farm families. They are exactly the voters we are trying to win.'], ['tom', 'Justice is not for sale.']],
    favor_drones: [['pryce', 'You passed the law against no-bid contracts in 2009.'], ['wade', 'The President will not endorse you anyway.'], ['dana', 'Everyone hates no-bid contracts.']],
    mideast_war: [['wade', 'You have warned about this for years. Be careful not to sound pleased.'], ['dana', 'Older and business Republicans are moving. If this lasts, it is your year.'], ['tom', 'Pray for the troops, publicly and first.']],
    oil_shock: [['dana', 'Farmers and older voters are coming home, Carol. Speak to their costs.'], ['wade', 'The MAGA base is tired. This is the moment.'], ['pryce', 'Diesel and the harvest. Nothing else.']],
    fbi_krantz: [['pryce', 'Let the investigation proceed. That is your position on everything, and it is right.'], ['wade', 'Gun owners will rally to Krantz. They were never ours.'], ['dana', 'Older voters want the truth.']],
    krantz_standoff: [['pryce', 'Carol, you negotiated the Aquifer Compact with ranchers and federal agencies. You can talk to both sides.'], ['wade', 'This is where competence stands out.'], ['dana', 'Nobody wants a shooting on a county road.']],
    affair_rumor: [['wade', 'Carol, this one is almost funny. Laugh it off.'], ['tom', 'Go to church on Sunday, like you have every Sunday for sixty years.'], ['pryce', 'Sue him. It would be the first thing all year that the whole party enjoys.']],
    donor_deal: [['pryce', 'You wrote the ethics law this offer breaks.'], ['wade', 'Three million dollars would pay for the whole registration drive.'], ['dana', 'Farmers with leaking wells are our voters.']],
    straw_poll: [['wade', 'The delegates will boo you. Speak to the voters watching at home.'], ['dana', 'Delegates are the most extreme Republicans in the state. Do not play to this room.']],
    white_house_trip: [['wade', 'The President has invited you? Go, and be gracious.'], ['dana', 'Cimarron voters notice when you are not here.'], ['pryce', 'Carol, it may be a trap. Go for one night.']],
    coburn_dui: [['wade', 'Do not attack him. Ask about his plans. He has none.'], ['kyle', 'Emma here. The dismissal is the story.']],
  },
};

// The shared events read each candidate's own advice.
const adviceOf = (s, e) => ADVICE_FOR[s?.player]?.[e.id] || e.advice || [];

// Advice for the rival stories that were written before the running mates moved to other candidates.
Object.assign(ADVICE_FOR.rick, {
  ellender_women: [['tom', 'Right to Life has never supported prosecuting women. Ruth went further than the pro-life movement.'], ['dana', 'This is the only abortion question that loses us Republican women by a large margin.'], ['wade', 'Dad, Dunmore will say you are hiding behind your running mate. Whatever you say, say it as a pastor.']],
});
