// ============================================================
// CANDIDATES — what you choose when you play each candidate: the pitch, the weak-spot label,
// the staff, the opening (the record you run on) and four running mates.
// The candidates' base appeal and profiles are in data.js (CANDIDATES).
// ============================================================

const PLAYABLE = ['castellano', 'dunmore', 'rick', 'krantz', 'vaskel', 'whitlock'];

// label: the weak spot your rivals attack. It rises with your own mistakes and costs you with every faction.
// start: extra starting support in every faction, to keep the six campaigns comparable in difficulty.
const PLAYER_INFO = {
  castellano: {
    label: 'Phony', labelDesc: 'A Harvard man in new boots. It rises when you look like you changed your beliefs for the job.',
    level: 'Standard', pitch: 'The Governor. Real power every week, the largest war chest, and every crisis in the state is yours to manage.',
    openingTitle: 'Your First Term', openingIntro: 'Every incumbent runs on a record. Which achievement from your first term will be the center of your campaign?',
    mateIntro: 'Your Lieutenant Governor, Travis Dunmore, is running against you, so you need a new running mate. Each one brings a faction closer to you, and each one comes with a story.',
    start: 2,
  },
  dunmore: {
    label: 'Grifter', labelDesc: 'A man who sells hats and supplements to the movement. It rises when your business and your show get mixed up.',
    level: 'Standard', pitch: 'The Lieutenant Governor with a podcast. The base loves you, the Chamber fears you, and everything you say on air can come back.',
    openingTitle: 'Your Brand', openingIntro: 'Four years of the show made you famous. What is the show known for?',
    mateIntro: 'Every movement needs a second voice. Choose your running mate.',
    start: 0,
  },
  rick: {
    label: 'Hypocrite', labelDesc: 'The preacher of small government with a private jet. It rises when your church\'s money becomes the story.',
    level: 'Standard', pitch: 'The pastor of a 9,000-member church. The best turnout machine in the state, and a lot of church money for reporters to read about.',
    openingTitle: 'Your Ministry', openingIntro: 'You have never held office. Voters know you through Cornerstone Church. What is the ministry best known for?',
    mateIntro: 'A pastor needs someone who knows the Capitol, or someone who widens the tent. Choose your running mate.',
    start: 1,
  },
  krantz: {
    label: 'Lawless', labelDesc: 'The sheriff who picks which laws to follow. It rises when your standoffs frighten ordinary voters.',
    level: 'Standard', pitch: 'The constitutional sheriff of Harlan County. Gun owners will follow you anywhere. The FBI already is.',
    openingTitle: 'Your Stand', openingIntro: 'You made your name by saying no to someone powerful. Which stand made you famous?',
    mateIntro: 'You are running as an outsider. Choose the person who will stand next to you.',
    start: 1,
  },
  vaskel: {
    label: 'Carpetbagger', labelDesc: 'A Californian who wants to buy a state. It rises when your money or your companies become the story, and by 1 for every $1M you pay from your own fortune', labelDesc: 'A Californian who wants to buy a state. It rises every time your money or your companies become the story.',
    level: 'Standard', pitch: 'The tech investor from California. Almost unlimited money, and every dollar you spend proves what your rivals say about you.',
    selfFund: true, money: 3,   // starts with $3M more, and pays from his own fortune when the war chest is empty
    openingTitle: 'Your Portfolio', openingIntro: 'You moved to Cimarron four years ago with a thesis. Which project proves it?',
    mateIntro: 'You need someone who makes you look like you belong here. Choose your running mate.',
    start: 19,  // his base appeal is low with the factions that vote most
  },
  whitlock: {
    label: 'Has-Been', labelDesc: 'A politician from another era. It rises when you look old, tired, or out of touch with the new party.',
    level: 'Hard', pitch: 'The last traditional conservative. You start at about 6%. The easier the difficulty, the more likely the war and the conditions that favor you.',
    openingTitle: 'Your Record', openingIntro: 'Thirty years in the Senate. What will you remind voters of first?',
    mateIntro: 'You need to reach voters who do not trust you yet. Choose your running mate.',
    start: 3,
  },
};

// Staff for each candidate. The ids are roles, so every event's advice works for every candidate:
// wade = campaign manager, dana = pollster, tom = faith outreach, kyle = digital, pryce = chief of staff.
const STAFF_TEAMS = {
  castellano: {
    wade:  { name: 'Wade Pickett', role: 'Campaign Manager', initials: 'WP', color: '#2b4c7e' },
    dana:  { name: 'Dana Reyes', role: 'Pollster', initials: 'DR', color: '#4f7a5a' },
    tom:   { name: 'Rev. Tom Hale', role: 'Faith Outreach Director', initials: 'TH', color: '#6b3fa0' },
    kyle:  { name: 'Kyle Brandt', role: 'Digital Director', initials: 'KB', color: '#9a4b2c' },
    pryce: { name: 'Gordon Pryce', role: 'Chief of Staff', initials: 'GP', color: '#5b6474' },
  },
  dunmore: {
    wade:  { name: 'Tanner Hoyt', role: 'Producer & Campaign Manager', initials: 'TH', color: '#b3561a' },
    dana:  { name: 'Roz Kemp', role: 'Pollster', initials: 'RK', color: '#4f7a5a' },
    tom:   { name: 'Pastor Dale Ingram', role: 'Faith Coalition', initials: 'DI', color: '#6b3fa0' },
    kyle:  { name: 'Zach Orr', role: 'Head of Clips', initials: 'ZO', color: '#9a4b2c' },
    pryce: { name: 'Marcy Dunmore', role: 'Chief of Staff (and wife)', initials: 'MD', color: '#5b6474' },
  },
  rick: {
    wade:  { name: 'Josh Dollins', role: 'Executive Pastor & Campaign Manager', initials: 'JD', color: '#553080' },
    dana:  { name: 'Beth Carraway', role: 'Pollster', initials: 'BC', color: '#4f7a5a' },
    tom:   { name: 'Elder Ray Sutton', role: 'Council of Pastors Liaison', initials: 'RS', color: '#6b3fa0' },
    kyle:  { name: 'Kaylee Morrow', role: 'Cornerstone Media', initials: 'KM', color: '#9a4b2c' },
    pryce: { name: 'Deb Farris', role: 'Church Treasurer', initials: 'DF', color: '#5b6474' },
  },
  krantz: {
    wade:  { name: 'Dale Voorhees', role: 'Undersheriff & Campaign Chairman', initials: 'DV', color: '#6d5a2c' },
    dana:  { name: 'Norma Leeds', role: 'Pollster', initials: 'NL', color: '#4f7a5a' },
    tom:   { name: 'Chaplain Ed Birch', role: 'Sheriff\'s Chaplain', initials: 'EB', color: '#6b3fa0' },
    kyle:  { name: 'Tyler Stamm', role: 'Posse Volunteer Coordinator', initials: 'TS', color: '#9a4b2c' },
    pryce: { name: 'Carl Whitfield', role: 'Lawyer', initials: 'CW', color: '#5b6474' },
  },
  vaskel: {
    wade:  { name: 'Nate Lindgren', role: 'COO & Campaign Manager', initials: 'NL', color: '#138a8a' },
    dana:  { name: 'Sasha Imrie', role: 'Head of Data', initials: 'SI', color: '#4f7a5a' },
    tom:   { name: 'Pastor Ben Otis', role: 'Faith Outreach (new hire)', initials: 'BO', color: '#6b3fa0' },
    kyle:  { name: 'Devin Cho', role: 'Growth Lead', initials: 'DC', color: '#9a4b2c' },
    pryce: { name: 'Margo Feld', role: 'General Counsel', initials: 'MF', color: '#5b6474' },
  },
  whitlock: {
    wade:  { name: 'Hal Brewer', role: 'Campaign Manager', initials: 'HB', color: '#6f86a6' },
    dana:  { name: 'Joan Tillis', role: 'Pollster', initials: 'JT', color: '#4f7a5a' },
    tom:   { name: 'Rev. Arthur Pell', role: 'Methodist Pastor', initials: 'AP', color: '#6b3fa0' },
    kyle:  { name: 'Emma Sandoval', role: 'Digital Director, age 24', initials: 'ES', color: '#9a4b2c' },
    pryce: { name: 'Peg Olsen', role: 'Chief of Staff for 30 Years', initials: 'PO', color: '#5b6474' },
  },
};

// ---------- Openings: the record each candidate runs on ----------
// flag (optional) is set when you choose it. Closing statements and victory speeches use each opening (debates.js, epilogue.js).
const OPENINGS = {
  castellano: [
    { id: 'income', title: 'Eliminated the state income tax',
      desc: 'Your signature law. It is popular with the base, but it has left a structural deficit and cuts to county aid.',
      fx: { liberty: 6, chamber: 3, seniors: -2 } },
    { id: 'rifle', title: 'Signed permitless carry and a Second Amendment Sanctuary Act',
      desc: 'State officers may not help enforce new federal gun restrictions. The Rifle Association gave you an A+.',
      fx: { guns: 6, maga: 2 } },
    { id: 'commandments', title: 'Required the Ten Commandments in every classroom',
      desc: 'The law is now in federal court. Evangelical leaders consider it your most important act.',
      fx: { faith: 6, seniors: 2, liberty: -2 } },
    { id: 'heartland', title: 'Launched "Operation Heartland," a state deportation program',
      desc: 'The state police work with ICE. 4,000 people were removed. Agricultural and meatpacking employers have lost workers.',
      fx: { maga: 6, online: 2, farm: -3, flag: 'raids' } },
    { id: 'dictionary', title: 'Removed "divisive" books from school libraries',
      desc: 'More than 300 titles were removed statewide. The law is popular with parents\' rights groups and opposed by librarians.',
      fx: { faith: 3, online: 4 } },
  ],
  dunmore: [
    { id: 'd_border', title: 'The Deportation Hour',
      desc: 'Every Monday, a full hour on the border, with sheriffs, ICE agents and families of victims. It made you the loudest immigration voice in the state.',
      fx: { maga: 6, online: 2, farm: -2 } },
    { id: 'd_uniparty', title: 'The Uniparty Files',
      desc: 'Weekly episodes that name the lobbyists, donors and legislators who "run Cimarron from the Capitol bar." The Chamber hates it.',
      fx: { online: 5, maga: 3, chamber: -3 } },
    { id: 'd_elections', title: 'Count Every Ballot by Hand',
      desc: 'Your crusade for hand counts forced recounts in six counties. No fraud was found. Your audience believes it was hidden.',
      fx: { maga: 5, seniors: 2, chamber: -2 } },
    { id: 'd_tiebreak', title: 'The Tie-Breaking Vote',
      desc: 'As president of the Senate, you killed Castellano\'s road-fee increase with your tie-breaking vote, live on the show.',
      fx: { liberty: 4, maga: 2, seniors: 1 } },
  ],
  rick: [
    { id: 'r_life', title: 'Cornerstone Life Centers',
      desc: 'Forty pregnancy centers across the state, funded by the church. Pro-life leaders call them the model for the nation.',
      fx: { faith: 6, seniors: 1 } },
    { id: 'r_revival', title: 'The Stadium Revival',
      desc: 'Sixty thousand people filled the Cimarron State stadium for three nights of prayer. The video has 20 million views.',
      fx: { faith: 4, online: 2, maga: 1 } },
    { id: 'r_academies', title: 'Cornerstone Academies',
      desc: 'Twelve Christian schools with 6,000 students. You led the fight for vouchers that pay for many of them.',
      fx: { faith: 3, liberty: 3, farm: -1 } },
    { id: 'r_relief', title: 'Cornerstone Relief',
      desc: 'Church disaster teams that arrive before FEMA does. After the 2027 floods, they rebuilt 400 homes in the Panhandle.',
      fx: { faith: 3, farm: 3, seniors: 1 } },
  ],
  krantz: [
    { id: 'k_atf', title: 'No ATF in Harlan County',
      desc: 'You ordered your deputies not to help federal agents enforce new gun rules, and dared the ATF to arrest you. It did not.',
      fx: { guns: 6, liberty: 2, seniors: -1 } },
    { id: 'k_blm', title: 'The Grazing Standoff',
      desc: 'In 2028 you stood with ranchers against the Bureau of Land Management for eleven days. The BLM left.',
      fx: { guns: 4, farm: 3, seniors: -2 } },
    { id: 'k_border', title: 'The Harlan Border Detail',
      desc: 'You sent volunteer deputies to help Texas at the southern border, on the county\'s own budget.',
      fx: { maga: 4, guns: 3 } },
    { id: 'k_jail', title: 'The Work Camp',
      desc: 'Inmates in Harlan County work on roads and farms. Crime in the county fell for five years in a row.',
      fx: { guns: 3, seniors: 3, maga: 1 } },
  ],
  vaskel: [
    { id: 'v_datacenters', title: 'The Pratt Junction Data Centers',
      desc: 'Three data centers, $4 billion of investment and 6,000 jobs promised. The first 1,500 jobs are already real.',
      fx: { chamber: 4, liberty: 2, online: 2 } },
    { id: 'v_charter', title: 'Freedomopolis',
      desc: 'Your planned charter city: its own rules, no zoning, no state labor code. The Liberty Caucus loves it. Farmers worry about the water.',
      fx: { liberty: 6, online: 2, farm: -2 } },
    { id: 'v_bitcoin', title: 'The Gas-Flare Bitcoin Mines',
      desc: 'Bitcoin mines that burn gas the oil fields used to waste. Profitable, loud, and very popular online.',
      fx: { liberty: 3, online: 4, seniors: -2 } },
    { id: 'v_tutors', title: 'Vaskel Academy',
      desc: 'Free AI tutoring for every rural school that asks. 214 schools use it. Test scores are up.',
      fx: { farm: 2, seniors: 2, liberty: 2 } },
  ],
  whitlock: [
    { id: 'w_budget', title: 'Twelve Balanced Budgets',
      desc: 'As Senate Majority Leader, you passed twelve balanced budgets in a row, without one tax increase.',
      fx: { chamber: 4, seniors: 2 } },
    { id: 'w_water', title: 'The Aquifer Compact',
      desc: 'Your 2019 water agreement kept Panhandle wells running through the drought. Farmers still thank you for it.',
      fx: { farm: 5, seniors: 1 } },
    { id: 'w_roads', title: 'The Rural Roads Act',
      desc: '4,000 miles of county roads repaired. Every small-town mayor in Cimarron has your photo somewhere.',
      fx: { farm: 3, seniors: 2, chamber: 1 } },
    { id: 'w_heartbeat', title: 'The First Heartbeat Law',
      desc: 'Few voters remember that you wrote Cimarron\'s first heartbeat bill, in 2013. You intend to remind them.',
      fx: { faith: 4, seniors: 1 } },
  ],
};
const RECORDS = Object.entries(OPENINGS).flatMap(([cid, list]) => list.map(r => ({ ...r, for: cid })));

// ---------- Running mates: four for each candidate, each with a story (see mates in events.js) ----------
const MATES = {
  castellano: [
    { id: 'pryce', name: 'Gordon Pryce', title: 'Business Wing',
      desc: 'Your Chief of Staff. Former president of the state Chamber of Commerce. Donors trust him. The base calls him "the establishment."',
      fx: { chamber: 8, farm: 2, maga: -4, rino: 2 } },
    { id: 'serrano', name: 'Rep. Lupe Serrano', title: 'Hispanic Conservatives',
      desc: 'State Representative from Pratt Junction and your protégé since your time as Attorney General. The daughter of Mexican immigrants who became citizens. Strong with working-class voters in Pratt Junction and the Panhandle.',
      fx: { farm: 3, chamber: 2, maga: 1, online: -1 } },
    { id: 'crowder', name: 'Mayor Beth Ann Crowder', title: 'Exurban Moms',
      desc: 'Mayor of Osgood and a former PTA president who led the fight over school library books. Popular with young mothers in the exurbs.',
      fx: { faith: 3, online: 2, seniors: 2, liberty: -1 } },
    { id: 'tilden', name: 'Sen. Wes Tilden', title: 'Senate Leadership',
      desc: 'Senate Majority Leader for eight years. He knows every legislator\'s price. Donors love him, and the base has never heard of him.',
      fx: { chamber: 5, seniors: 2, maga: -2, rino: 1 } },
  ],
  dunmore: [
    { id: 'voss', name: 'Declan Voss', title: 'New Right',
      desc: 'A 30-year-old policy fellow and writer. Argues that conservatives must "take control of the institutions." He is popular with young activists, and older voters do not trust him.',
      fx: { online: 8, liberty: -2, seniors: -3 } },
    { id: 'ruud', name: 'Tanya Ruud', title: 'MAHA Movement',
      desc: 'Founder of a statewide "health freedom" group. Opposes vaccine mandates and supports raw-milk sales. Large social media following among mothers.',
      fx: { online: 3, farm: 3, maga: 2, seniors: -2 } },
    { id: 'barlow', name: 'Chet "The Hammer" Barlow', title: 'Talk Radio',
      desc: 'A former pro wrestler who hosts the most popular afternoon talk-radio show in Cimarron. Older listeners love him.',
      fx: { maga: 3, seniors: 3, faith: -1 } },
    { id: 'vance', name: 'Kristi Vance', title: 'Election Integrity',
      desc: 'Founder of Cimarron Audit Now, the group that forced hand recounts in six counties. A hero to the base, and under investigation by the Secretary of State.',
      fx: { maga: 5, online: 2, seniors: -2, chamber: -2 } },
  ],
  rick: [
    { id: 'ellender', name: 'Sen. Ruth Ellender', title: 'Religious Right',
      desc: 'State Senator from Harlan. Wrote the state\'s abortion ban. Her church network overlaps with Cornerstone\'s, and she knows the Capitol.',
      fx: { faith: 6, seniors: 2, online: -1 } },
    { id: 'webb', name: 'Rev. Marcus Webb', title: 'City Churches',
      desc: 'Pastor of Greater Mount Zion in Lawrenceville, the largest Black congregation in the state. Pro-life, pro-police, and a Republican since 2016.',
      fx: { faith: 3, seniors: 2, chamber: 1, maga: -1 } },
    { id: 'duvall', name: 'Hannah Duvall', title: 'Homeschool Movement',
      desc: 'Founder of the Cimarron Home Educators network, 40,000 families strong. Online, organized and fierce.',
      fx: { faith: 3, online: 3, liberty: 1, seniors: -1 } },
    { id: 'kittredge', name: 'Rep. Amos Kittredge', title: 'Ranch Country',
      desc: 'A fourth-generation rancher from the Panhandle and chairman of the House Agriculture Committee.',
      fx: { farm: 5, guns: 2, online: -1 } },
  ],
  krantz: [
    { id: 'brannigan', name: 'Rep. Colt Brannigan', title: 'Gun Caucus',
      desc: 'State Representative from Sumner Valley. Wrote the Second Amendment Sanctuary Act. Former Army Ranger.',
      fx: { guns: 6, maga: 2, seniors: -1 } },
    { id: 'crane', name: 'Wyatt Crane', title: 'Patriot Militias',
      desc: 'Commander of the Cimarron Patriot Rangers, a volunteer militia that "trains to defend the Constitution." He stood with you at every standoff.',
      fx: { guns: 5, online: 2, seniors: -3, chamber: -2 } },
    { id: 'pettit', name: 'Cora Lynn Pettit', title: 'Water Rights',
      desc: 'A ranch widow who sued the federal government over water rights, and won. The face of the Panhandle water fight.',
      fx: { farm: 5, seniors: 2 } },
    { id: 'tate', name: 'Judge Orrin Tate (ret.)', title: 'Constitutional Order',
      desc: 'A retired state district judge who gives your constitutional arguments a legal voice. Older voters trust him.',
      fx: { seniors: 4, guns: 2, liberty: 1, online: -1 } },
  ],
  vaskel: [
    { id: 'mercer', name: 'Sloane Mercer', title: 'Crypto',
      desc: 'Founder of the Prairie Exchange, a crypto platform based in Pratt Junction. Young, rich and extremely online.',
      fx: { online: 4, liberty: 3, seniors: -3 } },
    { id: 'strand', name: 'Rep. Colby Strand', title: 'Liberty Caucus',
      desc: 'Chairman of the House Liberty Caucus. He votes no on almost everything, including some things the base wanted.',
      fx: { liberty: 5, guns: 1, faith: -1 } },
    { id: 'ostrowski', name: 'Gen. Mark Ostrowski (ret.)', title: 'Defense Tech',
      desc: 'A retired Air Force general who now advises your drone and satellite companies. A war hero to older voters.',
      fx: { seniors: 3, guns: 2, maga: 1, online: -1 } },
    { id: 'sykes', name: 'Jolene Sykes', title: 'Rural Broadband',
      desc: 'Founder of the broadband co-op that brought fiber internet to 40 rural towns. Proof that your ideas can reach farm country.',
      fx: { farm: 4, seniors: 1, liberty: 1 } },
  ],
  whitlock: [
    { id: 'ashby', name: 'Rep. Jim Ashby', title: 'Governing Conservatives',
      desc: 'A 20-year House member and chairman of the budget committee. Respected by both parties, and trusted by neither base.',
      fx: { chamber: 3, seniors: 2, rino: 1 } },
    { id: 'ferris', name: 'Mayor Tom Ferris', title: 'Crossover Voters',
      desc: 'Mayor of Fort Eisenhower, who left the Democratic Party in 2022. He brings business support and independent voters, if they register as Republicans in time.',
      fx: { chamber: 4, seniors: 1, maga: -2, rino: 2 } },
    { id: 'park', name: 'Dr. Helen Park', title: 'Farm Economy',
      desc: 'The agricultural economist at Cimarron State who warned about the soybean crisis a year early. Farmers listen to her.',
      fx: { farm: 4, chamber: 1 } },
    { id: 'delacroix', name: 'Col. Frank Delacroix (ret.)', title: 'Veterans',
      desc: 'A retired Army colonel and former commander at Fort Eisenhower. A Reagan Republican who speaks for veterans.',
      fx: { seniors: 3, guns: 2, faith: 1 } },
  ],
};
const RUNNING_MATES = Object.entries(MATES).flatMap(([cid, list]) => list.map(m => ({ ...m, for: cid })));
const mateOf = id => RUNNING_MATES.find(m => m.id === id);
