// ============================================================
// EPILOGUE — what happens after primary night.
// ============================================================

const DEMOCRAT = { name: 'Dr. Pam Lindqvist', desc: 'a pediatrician from Fort Eisenhower who ran on rural hospitals and school funding' };

// ---------- Promises: "questionId:answerIndex" → an action in your first 100 days ----------
const PROMISES = {
  'indict_verdict:1': 'Created an independent inspector general for state contracts.',
  'superintendents:1': 'Began a ten-year phase-out of property taxes, with the state replacing school funding.',
  'superintendents:2': 'Exempted homes from property taxes.',
  'hawk_diesel:0': 'Suspended the state diesel tax through the harvest.',
  'feud_water:0': 'Stopped new aquifer permits until a state water study is finished.',
  'feud_water:2': 'Signed a water law that gives farms first priority.',
  'commandments_ruling:3': 'Funded Ten Commandments billboards next to public schools.',
  'income_county:0': 'Created an emergency loan fund for rural counties that cannot pay their jails.',
  'income_county:2': 'Proposed a state lottery for county governments.',
  'rifle_roadrage:1': 'Opened free state firearms training centers in every region.',
  'rifle_roadrage:2': 'Signed a training requirement for gun carriers under 21.',
  'ruud_milk:2': 'Required yearly safety inspections for raw milk dairies.',
  'ellender_women:3': 'Funded twelve new state maternity homes.',
  'deport:0': 'Ordered the National Guard to support statewide immigration arrests.',
  'deport:1': 'Doubled the budget of Operation Heartland.',
  'deport:2': 'Asked Washington for an agricultural guest-worker program for Cimarron.',
  'deport:3': 'Broke ground on a 2,000-bed state immigration detention facility near Harlan.',
  'travel_ban:0': 'Signed a law making it a crime to help anyone travel out of state for an abortion.',
  'travel_ban:1': 'Signed a law making it a crime to help a minor travel out of state for an abortion.',
  'travel_ban:3': 'Signed restrictions on IVF procedures that destroy embryos.',
  'badminton:0': 'Created a state task force to enforce the girls\' sports law.',
  'badminton:1': 'Required sex verification for all girls in school sports.',
  'stolen:3': 'Banned voting machines and ordered hand counts in every county.',
  'measles:0': 'Ended all school vaccine requirements.',
  'measles:2': 'Expanded religious and personal exemptions from school vaccines.',
  'soybeans:1': 'Created a $200 million relief fund for farmers hurt by tariffs.',
  'drag:0': 'Cut state funding to libraries that host drag events for children.',
  'drag:1': 'Directed prosecutors to charge drag performances under the state obscenity law.',
  'drag:2': 'Signed a ban on drag performances where minors are present.',
  'teachers_carry:0': 'Funded firearms training and equipment for teachers.',
  'teachers_carry:2': 'Lowered the age for concealed carry to 18.',
  'teachers_carry:3': 'Funded armed resource officers in every public school.',
  'university:0': 'Replaced the university Board of Regents with conservative reformers.',
  'university:1': 'Eliminated university departments that teach DEI ideology.',
  'university:3': 'Founded the School of Civic Thought at the state university.',
  'pardons:0': 'Pardoned all twelve imprisoned Capitol protesters.',
  'pardons:1': 'Pardoned the nonviolent Capitol protesters.',
  'pardons:3': 'Pardoned the Capitol protesters and opened an investigation of their prosecutors.',
  'property_tax:0': 'Proposed a constitutional amendment to abolish property taxes.',
  'property_tax:1': 'Froze property taxes for homeowners over 65.',
  'property_tax:2': 'Proposed replacing property taxes with a higher sales tax.',
  'property_tax:3': 'Capped school district tax levies.',
  'wind:0': 'Signed a moratorium on new wind projects.',
  'wind:2': 'Ended state subsidies and tax breaks for wind energy.',
  'krantz_sheriff:3': 'Signed a law protecting sheriffs who refuse to enforce federal gun laws.',
  'podcast:0': 'Launched a weekly governor\'s show on streaming platforms.',
  'meatpacking:0': 'Loosened child labor laws for 14- and 15-year-olds.',
  'meatpacking:1': 'Expanded inmate work programs in meatpacking plants.',
  'meatpacking:3': 'Requested more H-2 work visas for Cimarron meatpacking plants.',
  'social_media:0': 'Signed age verification for social media and adult websites.',
  'social_media:2': 'Signed age verification for adult websites.',
  'social_media:3': 'Banned Chinese-owned apps on all devices on state networks.',
  'esg:0': 'Removed the state pension from ESG asset managers.',
  'esg:1': 'Banned ESG-linked firms from state contracts.',
  'esg:3': 'Moved part of the state pension into Bitcoin.',
  'fluoride:0': 'Banned fluoride in public drinking water.',
  'fluoride:2': 'Banned fluoride and ordered a review of all vaccine requirements.',
  'sanctuary:0': 'Sent the National Guard to Lawrenceville to enforce immigration law.',
  'sanctuary:1': 'Cut state funding to Lawrenceville until it cooperates with ICE.',
  'sanctuary:2': 'Brought charges against Lawrenceville council members under the anti-sanctuary law.',
  'prayer:0': 'Required daily prayer and Bible reading time in public schools.',
  'prayer:1': 'Required daily prayer time and funded chaplains in public schools.',
  'machine_guns:0': 'Declared firearms made in Cimarron exempt from federal regulation.',
  'machine_guns:1': 'Declared Cimarron-made firearms exempt from federal law and barred state police from assisting the ATF.',
  'snap:0': 'Required drug tests for food assistance recipients.',
  'snap:1': 'Added work requirements and time limits to food assistance.',
  'snap:2': 'Banned soda and candy purchases with food assistance.',
  'homeless:0': 'Banned public camping statewide.',
  'homeless:1': 'Expanded civil commitment for addiction and mental illness.',
  'homeless:3': 'Moved homeless funding to faith-based shelters.',
  'covid:0': 'Removed state officials who enforced COVID mandates.',
  'covid:1': 'Created a COVID accountability commission with subpoena power.',
  'covid:3': 'Banned all future vaccine and mask mandates.',
  'aquifer:1': 'Ordered a 15% cut in aquifer pumping, with compensation for farmers.',
  'aquifer:2': 'Funded voluntary water conservation incentives.',
  'crypto:0': 'Created a state Bitcoin reserve.',
  'crypto:2': 'Made gold and silver legal tender.',
  'secede:0': 'Called on the legislature to apply for a Convention of States.',
  'secede:2': 'Signed a resolution refusing to enforce "unconstitutional" federal laws.',
  'pledge:0': 'Proposed a sales tax cut in the first budget.',
  'pledge:3': 'Required that state spending fall every year.',
  'farmland:0': 'Forced the sale of farmland owned by Chinese citizens and companies.',
  'farmland:1': 'Banned new farmland purchases by citizens of adversary nations.',
  'farmland:2': 'Banned all foreign ownership of farmland.',
  'pipeline:0': 'Banned eminent domain for private pipelines.',
  'pipeline:2': 'Stopped the carbon dioxide pipeline project.',
  'vouchers:0': 'Signed universal school vouchers.',
  'vouchers:1': 'Signed universal school vouchers with guaranteed funding for rural schools.',
  'vouchers:3': 'Signed universal vouchers and required public schools to post their curriculum online.',
  'everify:0': 'Required E-Verify for every employer in the state.',
  'everify:3': 'Made it a state crime to hire workers who are in the country illegally.',
  'busing:0': 'Sent 500 National Guard members to the southern border.',
  'busing:2': 'Sent state police to support ICE operations inside Cimarron.',
  'ivf:2': 'Signed a law protecting IVF.',
  'dei_state:0': 'Ended all diversity programs in state agencies.',
  'dei_state:1': 'Required loyalty to state policy in agency hiring.',
  'dei_state:3': 'Required Constitution training for all state employees.',
  'national_guard_city:0': 'Deployed the National Guard in Fort Eisenhower to fight crime.',
  'porn:0': 'Banned online pornography in Cimarron.',
  'porn:1': 'Required strict age verification for adult websites.',
  'red_flag:1': 'Signed a law banning red flag orders.',
  'medicaid:1': 'Funded emergency grants for rural hospitals.',
  'medicaid:2': 'Expanded Medicaid with work requirements.',
  'medicaid:3': 'Proposed replacing Medicaid with health savings accounts.',
  'raw_milk_fda:0': 'Sent state troopers to block federal agents from enforcing food rules on Cimarron farms.',
  'raw_milk_fda:1': 'Signed the Food Freedom Act, making in-state raw milk sales legal.',
  'raw_milk_fda:3': 'Called on Congress to abolish the FDA and give its food powers to the states.',
  'h1b:0': 'Asked the President to end the H-1B program, and barred state contractors from using it.',
  'h1b:1': 'Supported H-1B visas for the Pratt Junction data centers.',
  'h1b:2': 'Signed a state tax penalty on companies that replace American workers with H-1B workers.',
  // events
  'judge_blocks:1': 'Continued to enforce the state immigration law in defiance of the federal court.',
  'right_to_life:0': 'Removed the rape and incest exceptions from the abortion ban.',
  'right_to_life:1': 'Removed all exceptions from the abortion ban.',
  'rifle_q:0': 'Signed permitless carry for 18-year-olds.',
  'growth_club:0': 'Cut the sales tax by two points.',
  'lawrenceville_murder:0': 'Signed "Emily\'s Law," requiring detention after any arrest of a person in the country illegally.',
  'shooting:0': 'Funded armed guards in every school.',
  'shooting:1': 'Raised the age to buy rifles to 21.',
  'pastors_breakfast:0': 'Funded chaplains in public schools.',
  'church_arrest:1': 'Barred immigration arrests at houses of worship, except for violent offenders.',
  'hospital:0': 'Reopened the Dry Fork hospital with a state grant.',
  'president_call:0': 'Fired the Secretary of State and endorsed tariffs on Canadian potash.',
  'president_call:1': 'Fired the Secretary of State.',
  'donor_deal:0': 'Vetoed the abandoned-well cleanup bill.',
};

// ---------- Your victory speech ----------
const SPEECH = {
  open: 'Tonight, the Republicans of Cimarron have spoken. They did not choose the loudest voice, and they did not choose the richest man. They chose a record, and a promise to finish the work.',
  record: {
    income: 'Four years ago, they said we could never end the income tax. We ended it. Every paycheck in this state is bigger because of it.',
    rifle: 'Four years ago, we made Cimarron a Second Amendment sanctuary. No federal agency will take the rights of a law-abiding citizen in this state while I am governor.',
    commandments: 'Four years ago, we put the Ten Commandments back in our classrooms. We will defend that law all the way to the Supreme Court.',
    heartland: 'Four years ago, we started Operation Heartland. We did what Washington would not do. And we are not finished.',
    dictionary: 'Four years ago, we gave parents control of what their children read. Parents, not bureaucrats, decide what is right for their children.',
    d_border: 'For four years, every Monday night, I told you the truth about the border. Starting in January, I get to fix it.',
    d_uniparty: 'I spent four years naming the people who ran this state from the Capitol bar. Tonight, they are the ones watching the results.',
    d_elections: 'I fought for every ballot to be counted by hand. Tonight, every one of them was counted, and they were counted for us.',
    d_tiebreak: 'When they tried to raise your fees, I cast the deciding vote. Tonight, you cast yours.',
    r_life: 'Thousands of children are alive today because our church said yes to life. Now this state will say it too.',
    r_revival: 'Sixty thousand of you filled a stadium to pray. Tonight, you filled the polls.',
    r_academies: 'I built schools for your children when the state would not. Now every family in Cimarron will have that choice.',
    r_relief: 'When the floods came, our church was there before the government. Now the government will learn from the church.',
    k_atf: 'I kept federal agents out of Harlan County. Starting in January, they will need permission to enter Cimarron.',
    k_blm: 'I stood on a road for eleven days so ranchers could keep their land. Tonight, the people of this state stood with me.',
    k_border: 'My deputies went to the border when Washington would not. Now the whole state will go.',
    k_jail: 'Crime in Harlan County fell five years in a row. We are going to do the same thing for the whole state.',
    v_datacenters: 'Four years ago I promised Pratt Junction jobs. I built them. Now I will build them everywhere.',
    v_charter: 'Freedomopolis proved that freedom works. Starting in January, the whole state is Freedomopolis.',
    v_bitcoin: 'I turned wasted gas into money. Now I will turn a wasteful government into a lean one.',
    v_tutors: 'Two hundred schools use the tutors we built, for free. In January, every school in Cimarron will.',
    w_budget: 'Twelve balanced budgets, and not one tax increase. That is the kind of government Cimarron voted for tonight.',
    w_water: 'I kept the Panhandle\'s wells running through the drought. I will keep this whole state running.',
    w_roads: 'I paved four thousand miles of your roads. Tonight, you gave me the road to the Governor\'s office.',
    w_heartbeat: 'I wrote this state\'s first heartbeat law in 2013. Some people forgot. Tonight, you remembered.',
  },
  faction: {
    maga: 'We will finish the job on the border. Every person who is in this state illegally will leave, and Cimarron will show the nation how it is done.',
    faith: 'We will defend life, from conception, without apology. And we will never ask a person of faith to hide that faith in a public square.',
    guns: 'Our rights do not come from Washington. They come from God, and in Cimarron they are protected by the people and their sheriffs.',
    liberty: 'We will keep cutting. Every dollar the government does not take is a dollar that belongs to a family, a farm or a small business.',
    online: 'We will take back the institutions that were turned against us, starting with our universities and our own state agencies.',
    farm: 'We will stand with the farmers and ranchers of this state, their land, their water and their right to earn a living.',
    chamber: 'We will make Cimarron the best state in America in which to build a business and hire a worker.',
    seniors: 'We will protect the people who built this state: their homes, their savings and their safety.',
  },
  closeFight: 'To the media and the consultants who said we were too much: we are only getting started. In November we will win, and in January we go back to work.',
  closeUnity: 'To everyone who voted for someone else tonight: this party is bigger than any primary. Tomorrow we begin again, together, and in November we will win.',
};

// ---------- If a rival wins ----------
const RIVAL_OUTCOMES = {
  dunmore: {
    general: 19,
    speech: 'Tonight, the uniparty lost. The consultants lost. The Chamber of Commerce lost. The people of Cimarron won. We will not govern like the last governor. We will not ask permission from Washington, from the courts or from the media. On day one, the deportations begin.',
    days: [
      ['Jan 12', 'Signs an executive order creating the Cimarron Deportation Task Force under the direct control of the governor\'s office.'],
      ['Jan 13', 'Names his podcast producer, Tanner Hoyt, as Chief of Staff.'],
      ['Jan 20', 'Orders state agencies to end all cooperation with federal agencies he calls "hostile," including the EPA and the Department of Education.'],
      ['Feb 3', 'Deploys the National Guard to Pratt Junction and the Panhandle. 2,100 people are detained in the first month.'],
      ['Feb 18', 'The Garnett Pork plant closes one of its two production lines. 600 jobs are lost.'],
      ['Mar 9', 'Signs a moratorium on all new wind and solar projects. Farmers in Sumner Valley lose lease contracts.'],
      ['Mar 30', 'A federal judge blocks the Task Force. Dunmore announces the state will ignore the ruling.'],
      ['Apr 20', 'Livestreams the signing of a law requiring hand counts in all future elections.'],
    ],
    later: 'One year later, Dunmore has the highest approval among Republican voters of any governor in the country and the lowest among all voters in the state\'s history. Cimarron is in open legal conflict with the federal courts. Meatpacking and dairy employers report a labor shortage of 11,000 workers. Dunmore is mentioned as a possible presidential candidate.',
  },
  rick: {
    general: 15,
    speech: 'We did not win tonight. The Lord won tonight. For too long, the people of faith in this state were told to vote for us and then be quiet. We will not be quiet anymore. Cimarron will be a state that honors God in its laws, in its schools and in its public life.',
    days: [
      ['Jan 12', 'Is sworn in on a family Bible and opens his inaugural address with a 20-minute prayer.'],
      ['Jan 15', 'Signs an order requiring daily prayer and Bible reading in all public schools. The ACLU sues the same day.'],
      ['Feb 2', 'Signs a law making it a felony to help anyone travel out of state for an abortion.'],
      ['Feb 20', 'Creates an Office of Faith and Family inside the governor\'s office, led by a Cornerstone Church elder.'],
      ['Mar 11', 'Signs a bill to close most retail businesses on Sundays. Walmart and two grocery chains announce legal challenges.'],
      ['Mar 25', 'Asks the legislature to prepare a law ending state recognition of same-sex marriages "when the Supreme Court permits it."'],
      ['Apr 8', 'A state audit finds that Cornerstone Church received $4 million in state grants for "family programs" in his first quarter.'],
      ['Apr 21', 'Removes 1,100 books from public libraries under a new "community standards" law.'],
    ],
    later: 'One year later, most of Governor Dollins\'s signature laws are blocked in federal court. Several employers announce they will not expand in the state. Church attendance and political organization in Cimarron are at record levels. His supporters call it a revival. His critics call it a theocracy. Both groups are larger than they were a year ago.',
  },
  krantz: {
    general: 18,
    speech: 'I have been a sheriff for sixteen years. I will be the same governor. The Constitution is the law. Not the ATF, not the Bureau of Land Management, not a judge in Denver. Starting tomorrow, Cimarron will protect its people from any government that forgets its limits, including its own.',
    days: [
      ['Jan 12', 'Signs an order declaring that no state officer will enforce any federal gun law.'],
      ['Jan 19', 'Names three sheriffs from the Constitutional Sheriffs movement to his cabinet.'],
      ['Feb 6', 'Asks the legislature to give county sheriffs final authority over law enforcement in their counties.'],
      ['Feb 24', 'Orders state police to block a Bureau of Land Management survey team near Dry Fork. The standoff lasts nine days.'],
      ['Mar 15', 'Creates a 5,000-member volunteer "State Guard" outside the National Guard\'s chain of command.'],
      ['Apr 2', 'The FBI\'s civil rights investigation of the Harlan County jail leads to indictments of two of his former deputies.'],
      ['Apr 19', 'Signs a law to transfer all federal land in Cimarron to the state. Federal courts block it within a week.'],
    ],
    later: 'One year later, Cimarron is the center of a national debate over the powers of sheriffs and states. The State Guard has 7,000 members and no clear legal status. Relations with federal agencies have collapsed. In rural counties, Governor Krantz is more popular than any governor in decades.',
  },
  vaskel: {
    general: 13,
    speech: 'Cimarron is not a government. Tonight it became a startup. For fifty years this state was run by people who never built anything. That ends now. We will cut, we will automate, and we will make Cimarron the fastest-growing state in America.',
    days: [
      ['Jan 12', 'Appoints six former employees of his companies to cabinet positions.'],
      ['Jan 22', 'Announces that 30% of state jobs will be replaced by software within two years.'],
      ['Feb 10', 'Signs a law creating charter cities exempt from state labor and zoning law. His own project is the first to apply.'],
      ['Mar 1', 'Creates a state Bitcoin reserve with $500 million of state funds.'],
      ['Mar 20', 'The state\'s new "AI-first" unemployment system fails for eleven days. 40,000 claims are delayed.'],
      ['Apr 5', 'Proposes the elimination of the sales tax, to be paid for by "efficiency."'],
      ['Apr 18', 'Reporters find that two of his companies won state contracts worth $210 million.'],
    ],
    later: 'One year later, the state workforce is 18% smaller, and waiting times for most state services are longer. The charter city has 1,400 residents. The Bitcoin reserve has gained 30%, then lost 45%. Vaskel says the state is "in beta."',
  },
  whitlock: {
    general: 24,
    speech: 'Tonight the Republican Party of Cimarron chose to govern. I know that many of you did not vote for me. I will be your governor anyway, and I will earn your trust with roads, water, schools and balanced budgets, not with anger.',
    days: [
      ['Jan 12', 'Restores $300 million in state aid to rural counties.'],
      ['Feb 1', 'Asks the legislature to delay the income tax repeal to close the structural deficit. Her own party refuses.'],
      ['Feb 20', 'Reaches an agreement with Washington on an agricultural guest-worker program.'],
      ['Mar 18', 'Dunmore and Pastor Rick announce a joint recall campaign.'],
      ['Apr 10', 'Signs a bipartisan water conservation plan for the Panhandle aquifer.'],
    ],
    later: 'One year later, Governor Whitlock has passed most of her budget with Democratic votes. The recall campaign has collected 190,000 signatures. Most of the Republican legislature treats her as an opponent.',
  },
};

// Outsider winners
Object.assign(RIVAL_OUTCOMES, {
  castellano: {
    general: 22,
    speech: 'Tonight, Cimarron chose a record over a rumor, and results over noise. Four years ago I promised to take this state back from Washington. I sued them forty-one times, and I am not finished. The next four years will be harder, and we will win them too.',
    days: [
      ['Jan 12', 'Is sworn in for a second term and announces a 42nd lawsuit against the federal government on his first day.'],
      ['Jan 20', 'Signs the second phase of the income tax repeal. The budget office projects a $600 million deficit.'],
      ['Feb 4', 'Doubles the budget of Operation Heartland and adds 300 state troopers to immigration duty.'],
      ['Feb 22', 'Vetoes a bill to restore state aid to rural counties. Four county sheriffs call it "a betrayal."'],
      ['Mar 10', 'Makes his first trip to Iowa. He says it is "a trade mission."'],
      ['Mar 28', 'Appoints his former law partner to the state Supreme Court.'],
      ['Apr 15', 'Opens a national political committee, "Litigate America." It raises $11 million in its first month.'],
    ],
    later: 'One year later, Governor Castellano is the most frequent Republican guest on national television and a leading name for 2032. In Cimarron, the income tax is gone, the deficit is large, and county governments are cutting deputies. Legislators of both parties say he is rarely in the Capitol.',
  },
  coburn: {
    general: 21,
    speech: 'Tonight Cimarron picked a winner. I have never run for anything but the end zone, and I have never lost the big game. We are going to cut your gas bill, secure our roads, and make this the proudest state in America.',
    days: [
      ['Jan 12', 'Signs an executive order cutting the state gas tax to zero. The budget office warns of a $600 million shortfall.'],
      ['Jan 20', 'Names his former sports agent as Chief of Staff.'],
      ['Feb 5', 'Launches "Operation Open Road," placing state troopers at interstate entrances to check immigration status.'],
      ['Feb 26', 'A federal court blocks the checkpoints.'],
      ['Mar 12', 'Announces a state bid to bring a professional football team to Fort Eisenhower.'],
      ['Apr 1', 'Proposes a 15% cut to the state university to pay for the gas tax cut.'],
      ['Apr 18', 'Signs a ban on transgender athletes in adult recreational leagues.'],
    ],
    later: 'One year later, Governor Coburn is the most popular politician in the state and the least experienced one. The gas tax cut has left a $700 million hole in the budget, which the legislature fills by cutting schools and roads. He is often mentioned as a future Senate candidate.',
  },
});

// ---------- Your concession (if you lose) ----------
// What happens to you after a defeat, by candidate and by the kind of concession.
const CONCESSION_FUTURE = {
  dunmore: { endorse: 'You endorse the winner and go back to the show. Your audience doubles in a year. In 2032, you run for the U.S. Senate as the movement\'s candidate.', silent: 'You go back to the show and never mention the winner by name. Your audience grows. Party leaders stop returning your calls, and you do not care.', recount: 'The recount changes nothing. Your audience believes every word you say about it. You become a national figure in the election-integrity movement, and you never hold office again.' },
  rick: { endorse: 'You return to Cornerstone and preach on reconciliation the next Sunday. The church network you built becomes the most sought-after endorsement in the state.', silent: 'You return to your pulpit. Attendance at Cornerstone falls for the first time in a decade, and some pastors on the Council quietly replace you.', recount: 'Your church lawyers lead the recount. It fails. The IRS opens an audit of Cornerstone\'s political activity six months later.' },
  krantz: { endorse: 'You go back to Harlan County and win a fifth term as sheriff without opposition. Other states invite you to speak about the constitutional sheriff movement.', silent: 'You go back to Harlan. The new governor cuts state grants to your department, and your deputies know why.', recount: 'You refuse to recognize the result in Harlan County for nine days. The state police chief asks the courts to intervene. Your career ends in a hearing room.' },
  vaskel: { endorse: 'You endorse the winner and fund the party\'s general-election effort. In two years, your data centers employ 9,000 people. Nobody calls you a Californian anymore.', silent: 'You move your family back to California for "a year." Two of your projects in Pratt Junction are paused.', recount: 'You spend $6 million on the recount. It changes 212 votes. The Ledger calls it "the most expensive tantrum in state history."' },
  whitlock: { endorse: 'You endorse the nominee, which surprises everyone. A year later, you chair a bipartisan commission on the aquifer, and both parties call it the best work in the Capitol.', silent: 'You retire to your ranch near Sumner. Your memoir, "The Party I Knew," becomes a national bestseller.', recount: 'You ask for a recount in only two counties, as the law allows. It changes nothing, and you concede with a short, graceful letter that is read on the Senate floor.' },
};
const concessionFuture = (s, c) => s.player === 'castellano' ? c.future : (CONCESSION_FUTURE[s.player]?.[c.id] || c.future);
const CONCESSION = [
  { id: 'endorse', text: 'Concede tonight and endorse the winner.',
    speech: (w, obj) => `"The voters have made their decision, and I respect it. I called ${w} a few minutes ago to congratulate ${obj}. ${w} will be our nominee, and will have my full support in November."`,
    future: 'You leave office in January with your reputation in the party intact. Party leaders remember that you conceded with dignity. Within a year, you are appointed to a senior position in the President\'s administration. You are considered a strong candidate for the U.S. Senate in 2032.',
    general: 2 },
  { id: 'silent', text: 'Concede, but do not endorse the winner.',
    speech: (w, obj, s) => `"The voters have spoken. I will spend the next months with my family, and I will continue to serve the people of Cimarron ${s && s.player === 'castellano' ? 'until my term ends' : 'in every way I can'}."`,
    future: 'Your refusal to endorse is noticed. Many party activists see you as bitter. You return to private life as a partner at a law firm in Fort Eisenhower. You appear occasionally on cable news as a critic of the new governor.',
    general: 0 },
  { id: 'recount', text: 'Refuse to concede and demand a recount, citing irregularities.',
    speech: () => '"Tonight\'s results are not final. We have received reports of irregularities in several counties, and every legal vote must be counted. We will not concede until it is."',
    future: 'The recount takes three weeks. It changes the result by fewer than 300 votes. The state party\'s executive committee votes to censure you. Your standing with election-integrity activists rises, and for a time you are a regular guest on national conservative media. Your political career in Cimarron is over.',
    general: -3 },
];

// ---------- Consequences of your campaign (flag → text) ----------
// acts: the line describes something done in office. A challenger who lost never held office, so it is not shown.
const EPILOGUE = [
  { flag: 'alcatraz', acts: true, text: 'The state detention facility opens with 2,000 beds. The lawsuit from the detained Navy veteran continues in federal court and becomes a national case about citizens held in immigration detention.' },
  { flag: 'raids', acts: true, text: 'Operation Heartland continues. The Garnett Pork plant and three large dairies report a permanent labor shortage. Two small meatpacking plants in the Panhandle close.' },
  { flag: 'btc', acts: true, text: 'The pension fund\'s Bitcoin position becomes the subject of legislative hearings. The retirement system\'s trustees ask for a law to prevent it happening again.' },
  { flag: 'child_labor', acts: true, text: 'The child labor reform remains law. Workplace injuries among minors in Cimarron rise 40% the following year, and the federal Labor Department opens an investigation.' },
  { flag: 'pardons', acts: true, text: 'The pardoned Capitol protesters become a political force. Two are elected to the legislature, where they lead a caucus of their own.' },
  { flag: 'podcast', text: 'Your weekly show continues after the campaign and becomes one of the most popular conservative programs in the region.' },
  { flag: 'no_prop_tax', acts: true, text: 'The promise to abolish property taxes leads to a constitutional amendment fight. Rural school districts warn that dozens of schools could close.' },
  { flag: 'defy', acts: true, text: 'Your defiance of the federal court becomes a model for other Republican governors, and a central case in a growing conflict between the states and the federal judiciary.' },
  { flag: 'donor_deal', acts: true, text: 'Harold Voigt\'s companies leave 1,200 abandoned wells unplugged. Panhandle farmers file a class-action lawsuit.' },
  { flag: 'war', text: 'The war in the Middle East lasts eleven weeks. Gas prices stay above $5 until the following spring. In Cimarron, the war and the oil shock become the main issue of the fall, and several Republican legislators close to the President lose their primaries two years later.' },
  { flag: 'war_hawk', text: 'You stood with the President on the war. His strongest supporters remember it. So do the farmers who paid $7 for diesel.' },
  { flag: 'war_dove', text: 'You opposed the war from the first day. The New Right now counts you as one of its own, and the President\'s team does not.' },
  { flag: 'indicted', text: s => s.flags.tolliver_pardoned ? 'You pardoned Mark Tolliver. A federal grand jury opens an investigation into the pardon, and the legislature considers a constitutional amendment to limit the governor\'s pardon power.'
      : s.flags.official1 ? 'You are never charged, but "Official 1" follows you. Every profile of you mentions it, and so does every Democratic ad in the fall.'
      : s.seenEvents.includes('indict_verdict') ? 'Mark Tolliver serves his sentence. The case is closed, and your name is not in it.'
      : 'Your former Chief of Staff is convicted the following year. The trial keeps your name in the news for months.' },
  { flag: 'hale_out', text: 'Dr. Priya Hale and her husband leave the Republican Party. She later testifies before the legislature about the online attacks against her, which continued for months.' },
  { flag: 'tencom_defy', acts: true, text: 'The Ten Commandments stay on classroom walls in defiance of the appeals court. Three superintendents are held in contempt, and the case reaches the Supreme Court the following spring.' },
  { flag: 'mateo_deported', acts: true, text: 'Mateo Ruiz enrolls at a university in Monterrey. Sumner High retires his jersey number. In the next county election, the Sumner Republican chairman, his old coach, resigns from the party.' },
  { flag: 'library_cut', acts: true, text: 'The Osgood library loses its state funding and cuts its hours in half. "The Wheat Line" becomes the best-selling book in Cimarron history.' },
  { flag: 'voss_kept', text: 'Declan Voss becomes the most famous Lieutenant Governor in the country. His anonymous posts are quoted in every profile of him, and he does not seem to mind.' },
  { flag: 'prosecute_women', text: 'A bill to prosecute women who travel for abortions is introduced in the next session. It fails in committee, but the vote becomes the center of the general election in three legislative districts.' },
  { flag: 'stolen_valor', text: 'Colt Brannigan resigns from the legislature the following year. Veterans\' groups in Cimarron stop inviting your campaign to their events.' },
  { flag: 'mate_swap', text: s => `You replaced ${RUNNING_MATES.find(m => m.id === s.formerMate)?.name || 'your running mate'} during the campaign. Political reporters use it as an example of how fast a primary can change a ticket, and your former running mate does not return your calls.` },
  { flag: 'renner_pardon', acts: true, text: 'You pardoned Cal Renner. He never repays the farm families. Three of them sue the state, and one runs for the legislature against your ally in the Panhandle, and wins.' },
  { flag: 'drone_deal', acts: true, text: 'The Liberty Drone contract becomes the subject of a federal inspector general\'s report. Half of the drones never fly. The President\'s son calls the report "a witch hunt."' },
  { flag: 'self_loan', text: 'You lent your campaign $1 million. Donors help you repay about half of it. You pay the rest over six years.' },
  { flag: 'emails_clean', text: 'Your decision to release four thousand emails becomes a standard example in ethics classes at the state university.' },
  { flag: 'oppo_war', text: 'The negative campaign between you and Dunmore leaves lasting damage. The two factions of the state party do not cooperate for years.' },
];
const EPILOGUE_RINO_HIGH = 'The RINO label stays with you. Dunmore\'s movement continues to treat you as an enemy of the base, and you will likely face a primary challenge in any future race.';
const EPILOGUE_RINO_LOW = 'No one was able to make the RINO label stick to you. The base considers you one of its own.';

// ---------- Victory speeches ----------
// Your speech and every rival's speech are built from the campaign: how the race was won, the President,
// the war, your running mate, your biggest decisions and the rival you beat. {loser} = "Governor <your last name>".
const YOUR_SPEECH = {
  open: {
    runoff: 'Three weeks ago, they said this campaign was finished. Tonight, after a primary and a runoff, the Republicans of Cimarron have answered twice, and the answer is the same both times.',
    landslide: 'Tonight was not close. In every region of this state, from the Panhandle to Fort Eisenhower, the Republicans of Cimarron chose to finish the work we started.',
    close: 'Tonight was close, and I will not pretend it was not. Every vote in this race was earned, and I will spend the next four years earning the ones I did not get.',
    presAgainst: 'The President endorsed someone else in this race. I respect him, and I will work with him every day. But tonight the Republicans of Cimarron made their own choice.',
    presFor: 'I want to begin by thanking the President of the United States, who stood with this campaign when it mattered most. Tonight, Cimarron stood with us too.',
    comeback: 'In the spring, the polls had us in third place. Reporters asked me when I would drop out. Tonight, I have an answer for them.',
  },
  mate: {
    brannigan: 'I want to thank Colt Brannigan, a soldier who never stopped serving, and who will be the next Lieutenant Governor of Cimarron.',
    ellender: 'I want to thank Senator Ruth Ellender, who has fought for the unborn longer than most people in this room have been in politics.',
    voss: 'I want to thank Declan Voss, who reminded this party that the young people of Cimarron are not our future. They are our present.',
    ruud: 'I want to thank Tanya Ruud and the mothers of this state, who taught every politician in Cimarron to listen before they speak.',
    pryce: 'I want to thank Gordon Pryce, who does not give speeches, does not want the credit, and without whom none of this would have happened.',
    serrano: 'I want to thank Lupe Serrano, the daughter of immigrants who became citizens, and the next Lieutenant Governor of Cimarron.',
    crowder: 'I want to thank Beth Ann Crowder and the mothers of Osgood, who showed this state what it means to fight for your children.',
    tilden: 'I want to thank Wes Tilden, who knows where every vote in the Capitol is, and who found the ones we needed.',
    barlow: 'I want to thank Chet Barlow, who told the truth on the radio every afternoon when nobody else would.',
    vance: 'I want to thank Kristi Vance, who never stopped asking the questions they did not want asked.',
    webb: 'I want to thank Reverend Marcus Webb, who reminded this state that the church of Jesus Christ is bigger than any one neighborhood.',
    duvall: 'I want to thank Hannah Duvall and forty thousand homeschool families, who are raising the next generation of this state.',
    kittredge: 'I want to thank Amos Kittredge, whose family has worked the same land in the Panhandle for four generations.',
    crane: 'I want to thank Wyatt Crane and the men and women who stood with us on every road we had to stand on.',
    pettit: 'I want to thank Cora Lynn Pettit, who beat the federal government in court, and who will now help run the state.',
    tate: 'I want to thank Judge Orrin Tate, who has read the Constitution more times than anyone in this room, including me.',
    mercer: 'I want to thank Sloane Mercer, who reminded this campaign that the future is already here.',
    strand: 'I want to thank Colby Strand, who has said no to more bad bills than anyone in the history of this state.',
    ostrowski: 'I want to thank General Mark Ostrowski, who served this country for thirty years, and is not finished.',
    sykes: 'I want to thank Jolene Sykes, who brought the internet to forty towns that Washington forgot.',
    ashby: 'I want to thank Jim Ashby, who has balanced more budgets than any legislator alive.',
    ferris: 'I want to thank Tom Ferris, who left one party because it left him, and helped us build a bigger one.',
    park: 'I want to thank Dr. Helen Park, who warned us about the soybean crisis before anyone else would listen.',
    delacroix: 'I want to thank Colonel Frank Delacroix and every veteran who stood with this campaign.',
  },
  mateSwap: 'This ticket changed during the campaign. That is never easy, and I thank everyone who stayed with us when it happened.',
  moments: [
    { cond: s => s.flags.tolliver_pardoned, text: 'I kept my word to a friend this year, when it would have been easier not to. You will always know where I stand.' },
    { cond: s => s.flags.official1, text: 'This year, the courts and the press tried to write my story for me. Tonight, the voters wrote it themselves.' },
    { cond: s => s.flags.emails_clean, text: 'This year I opened four thousand of my own emails to the public, because I have nothing to hide from the people I work for.' },
    { cond: s => s.flags.tape2, text: 'I said something wrong at a dinner years ago, and you heard it. I owned it, and you gave me a second chance. I will not waste it.' },
    { cond: s => s.flags.defy || s.flags.tencom_defy, text: 'When a federal judge told Cimarron what it could not do, we did not ask permission. We will not start asking now.' },
    { cond: s => s.flags.war_dove, text: 'When the war began, I said that America First means no new wars. It was not popular in Washington. It was right in Cimarron.' },
    { cond: s => s.flags.war_hawk, text: 'When Americans were attacked, I stood with our troops and our President from the first day. I have never been ashamed of that.' },
    { cond: s => s.seenEvents.includes('tornado') && s.log.some(l => l.q.includes('EF-4') && l.a.startsWith('Suspend')), text: 'When the tornado came to Sumner, I stopped campaigning and went to work. The families of Sumner are rebuilding, and we will not leave until they are home.' },
    { cond: s => s.flags.alcatraz, text: s => isGov(s) ? 'We are building a detention center so that no one who breaks our immigration laws is released into our towns again.' : 'I promised a detention center so that no one who breaks our immigration laws is released into our towns again. We will build it.' },
    { cond: s => s.flags.pardons, text: s => isGov(s) ? 'I pardoned the protesters that Washington wanted to make an example of. I would do it again.' : 'I promised to pardon the protesters that Washington wanted to make an example of. In January, I will.' },
    { cond: s => s.flags.resort_seen && !isGov(s), text: 'When the ice storm came and the Governor was on a beach in Mexico, we were in the Panhandle. Cimarron remembered.' },
    { cond: s => s.flags.mateo_deported, text: 'Some decisions this year were hard. I made them because the law must mean the same thing for everyone.' },
    { cond: s => s.flags.self_loan, text: 'When this campaign ran low on money, I put in my own. I bet on you, and you did not let me down.' },
    { cond: s => s.flags.oppo_war && s.finalRunnerUp === 'dunmore', text: 'This was a hard campaign. Travis and I said hard things about each other. Tomorrow, this party has to become one party again.' },
  ],
  endorsements: n => `I am grateful to the ${n} organizations that stood with this campaign, and to every pastor, sheriff, farmer and volunteer who knocked on a door.`,
  rival: {
    castellano: { fight: 'To Governor Castellano: you sued Washington forty-one times. Tonight, the voters of Cimarron ruled against you.', kind: 'To Governor Castellano: thank you for four years of service. The work you started is in good hands.' },
    dunmore: { fight: 'To Travis Dunmore: you have a microphone. Tonight, I have a mandate. Keep talking. I will keep working.', kind: 'To Travis Dunmore and his supporters: you fought hard, and you made this party listen. I heard you.' },
    rick: { fight: 'To Pastor Rick: you preach well. But tonight the people of Cimarron chose a governor, not a preacher.', kind: 'To Pastor Rick and the churches that stood with him: your faith is welcome in my administration, every day.' },
    krantz: { fight: 'To Sheriff Krantz: the law in this state is written by the people\'s representatives, and tonight the people spoke.', kind: 'To Sheriff Krantz: go back to Harlan with my respect. We will need you there.' },
    vaskel: { fight: 'To Brent Vaskel: you spent more money than anyone in the history of this state. Cimarron is still not for sale.', kind: 'To Brent Vaskel: you brought new ideas and new jobs to this state. I want both of them to stay.' },
    whitlock: { fight: 'To Senator Whitlock: the party you remember is gone. The party that voted tonight is the one I lead.', kind: 'To Senator Whitlock, who served this state for thirty years: thank you. Some of your ideas are better than this party admits.' },
    coburn: { fight: 'To Jake Coburn: this is not a football game, and tonight the scoreboard is final.', kind: 'To Jake Coburn: you are still the greatest quarterback this state has ever had. I hope you will help us govern it.' },
  },
  close: {
    war: 'Our country is at war, and families in Cimarron are paying for it at the pump and at the harvest. I will not forget them for one day. In November we will win, and then we go back to work.',
    fight: 'To the media and the consultants who said we were too much: we are only getting started. In November we will win, and in January we go back to work.',
    unity: 'To everyone who voted for someone else tonight: this party is bigger than any primary. Tomorrow we begin again, together, and in November we will win.',
    runoff: 'We won this nomination twice. Now we go win it a third time, in November, for every Cimarronian.',
  },
};

const RIVAL_SPEECH = {
  castellano: {
    open: { runoff: 'They needed a runoff to learn what I knew in the spring: Cimarron does not fire a governor who keeps his word.', landslide: 'I have argued cases before the Supreme Court. Tonight, the verdict was unanimous.', president: 'I want to thank the President, who knows the difference between a fighter and a lawyer who wins.', default: 'Four years ago I asked for your trust. Tonight you renewed it.' },
    you: { rino: '{loser} spent this campaign saying I was not conservative enough. The voters read the record.', scandal: '{loser} ran a campaign that will be studied, mostly by lawyers.', default: '{loser} called to concede. I thanked {loser} for a hard campaign. Now we govern.' },
    war: 'Our troops are at war, and our farmers are paying for it. I will fight for both, in Washington and in court if I have to.',
    close: 'Tomorrow at eight, I will be at my desk in the Capitol. At nine, I expect to file a lawsuit.',
  },
  dunmore: {
    open: { runoff: 'They needed two elections to beat us. They lost both.', landslide: 'Look at this map. Every region. Every county that matters. This was not a primary. It was a verdict.', president: 'First, I want to thank the President. He saw this coming before anybody. He always does.', default: 'Can you hear that? That is the sound of the establishment losing.' },
    beat: '{loser} ran hard, and every one of {loser}\'s voters is welcome in this movement. The door is open. The show is on at six.',
    you: { rino: '{loser} spent four years governing like a Democrat with better manners. Tonight the base remembered.', scandal: '{loser} thought the voters would forget the tapes and the deals. Our listeners never forget anything.', default: '{loser} called and conceded. I thanked {loser}. Then I went back to work, because the work starts tonight.' },
    war: 'And to the President: we are with you, but Cimarron farmers need diesel. We will say so, loudly.',
    close: 'Tomorrow morning, the podcast goes live at six, like always. The difference is that now we have a state.',
  },
  rick: {
    open: { runoff: 'We prayed for this victory twice. The Lord answered twice.', landslide: 'Brothers and sisters, the churches of Cimarron voted tonight, and they voted together.', president: 'The President endorsed a man of faith, and the people of faith answered.', default: 'Let us begin tonight the way we began this campaign: with a word of thanks to God.' },
    beat: '{loser} fought a good fight. I will pray for {loser} tonight, and I hope {loser}\'s supporters will pray with us.',
    you: { rino: '{loser} asked believers for their votes and then asked them to be quiet. Tonight, they spoke.', scandal: 'I pray for {loser}. Scripture tells us that what is done in darkness will come to light, and this year it did.', default: '{loser} is a good person who chose the world\'s way. I will pray for {loser}, and I will govern the Lord\'s way.' },
    war: 'We pray for our soldiers tonight, and for the peace of Jerusalem.',
    close: 'On Sunday, I will preach at Cornerstone, like I have for twenty-two years. On Monday, I will begin to govern. The message will be the same.',
  },
  krantz: {
    open: { runoff: 'It took two elections. Harlan County is used to long fights.', landslide: 'I am not much for speeches. The numbers tonight say enough.', president: 'I thank the President for his trust. A sheriff does not forget who stood with him.', default: 'I will keep this short. Sheriffs usually do.' },
    beat: '{loser} called me tonight. I said what I always say: the Constitution does not change after an election.',
    you: { rino: '{loser} tried to be everybody\'s friend. In my county, that is how you lose the trust of everybody.', scandal: '{loser} will have to answer some questions now. That is not politics. That is the law, and it applies to governors too.', default: '{loser} called me. We have not always agreed. I told {loser} the same thing I tell everyone: the Constitution does not change after an election.' },
    war: 'Our boys are overseas tonight. The ones at home will be protected by their own state.',
    close: 'Tomorrow I drive to Fort Eisenhower. I am bringing my badge. I intend to keep wearing it.',
  },
  vaskel: {
    open: { runoff: 'We ran a second round, iterated, and shipped. That is how you build anything.', landslide: 'The data were clear for months. Tonight the voters confirmed the model.', president: 'Thank you to the President, who understands that the future is built, not inherited.', default: 'Four years ago I moved here with a laptop and a thesis: that Cimarron could be the fastest-growing state in America. Tonight the thesis won.' },
    beat: '{loser} ran a legacy campaign. We ran a better product. I thank {loser} for the competition.',
    you: { rino: '{loser} ran the state like a committee. We will run it like a company that intends to win.', scandal: '{loser} ran the old model: donors, favors, quiet deals. The old model just failed its audit.', default: '{loser} did a decent job with the old system. I thank {loser}. The old system is being deprecated.' },
    war: 'Energy prices prove one thing: states that do not build their own power will be held hostage by the world. Cimarron will build.',
    close: 'Tomorrow at 7 a.m. my transition team begins. Every state agency will receive one question: what would you do with half the budget and twice the software?',
  },
  whitlock: {
    open: { runoff: 'Many people told me that a candidate like me could not survive a runoff in this party. I am grateful they were wrong.', landslide: 'I did not expect to stand here tonight. I am humbled, and I am ready.', president: 'I will say plainly: I disagree with the President about many things, and I will work with him on all of them.', default: 'Good evening. I would like to begin by thanking every candidate in this race, including the ones who said terrible things about me.' },
    beat: '{loser} ran a serious campaign, and some of {loser}\'s ideas will be in my administration.',
    you: { rino: '{loser} and I agreed on more than either of us admitted. I will try to finish some of that work.', scandal: 'This year reminded us that public office is a public trust. I will begin my term with an ethics law, and I will sign it first.', default: '{loser} served this state for four years, and served it seriously. I thank {loser} for that.' },
    war: 'War is a serious thing. So is the price of diesel. I will talk honestly about both, which may be the most radical thing I do.',
    close: 'The anger of the last few years has not built one road, filled one reservoir or taught one child to read. Tomorrow, we do those things.',
  },
  coburn: {
    open: { runoff: 'Overtime. I love overtime.', landslide: 'That is a blowout, folks. I have been on the right side of a few of those, and this is the best one.', president: 'The President called me before anybody else tonight. He said, "Jake, you won big." He was right.', default: 'Cimarron, we did it. Game over. We win.' },
    beat: '{loser} played a tough game, and tough games make better teams.',
    you: { rino: '{loser} played not to lose. You never win like that. Never.', scandal: '{loser} got caught holding the ball too long. It happens. Not to me.', default: '{loser} played a good game, and called me like a pro. Respect.' },
    war: 'Our troops are the real team. Every one of them. We are going to take care of them, and their families at the gas pump.',
    close: 'Tomorrow we get to work. Early. Coach always said the game is won in practice, and practice starts at six.',
  },
};
